### ISSUE TITLE
hovering on disabled state label should not show hyperlink

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#100]
Mac 10.11.4 + Chrome 49.0

1. open https://www.topcoder-qa.com/search/members/?q=china
2. on the first row, hover on “No track selected” tag, observe

expected: it should not show hyperlink since it’s in disabled state.

actual: see screenshot, it still show hyperlink

![qq20160409-41 2x](https://cloud.githubusercontent.com/assets/4590317/14402533/683f4b0c-fe6b-11e5-8924-df5b070eb85b.png)

**Comment by callmekatootie** [comment]
The hover link takes you to the user's profile - it has got nothing to do with the disabled state
