### ISSUE TITLE
Input should autofocus on search field when hovering over search icon

### ISSUE THREAD

**Issue by Colinh84** [appirio-tech/topcoder-app-r#101]
When hovering over search icon on far right of screen in desktop mode, search dropdown appears but does not focus input on the field.

Expected:
when hovering over the search icon, user should be able to start typing search query without clicking on search field which appears below.

Actual:
Have to manually focus on appearing search field after hovering on icon.

**Requirements**
- [ ] Please adhere to the code style specified in the readme.
- [ ] Make sure the component is rendered correctly on all screen sizes as specified in the designs

**Resources**
 -

**Comment by callmekatootie** [comment]
Not necessarily
