### ISSUE TITLE
Different size of fields

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#102]
Environment

Safari

Description

1) Access page link without to login.

2) Try to login.

actual: the fields have different size.

expected: the fields must have the same size.

see attach!

![safari](https://cloud.githubusercontent.com/assets/18361424/14402539/a40ee590-fe41-11e5-87cb-5b83240b0e9d.png)

**Comment by callmekatootie** [comment]
Login page not in scope!
