### ISSUE TITLE
showing error if search for only space key 

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/topcoder-app-r#103]
1. Launch the site
2. Login with username sweta.ipec   pwd: sweta@123
3. go to search box
4. enter space key
5. click enter

Expected Result: Should show "NO matching result Found"
Actual Result:  showing error

![image](https://cloud.githubusercontent.com/assets/16131461/14402542/af647968-fe56-11e5-8f55-dad0f6895a95.png)

**Comment by callmekatootie** [comment]
Duplicate - the text needs to be trimmed
