### ISSUE TITLE
Different size of text

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#104]
Environment

Safari 9.0

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Press on the search icon glass from the top right of page.

actual: observe the default text  as is written with lowercase.

expected: display the correct default text.

![safari-text](https://cloud.githubusercontent.com/assets/18361424/14402549/f7152ace-fe41-11e5-8877-5e710e3b2f63.png)

**Comment by callmekatootie** [comment]
Can't seem to reproduce this one:

![image](https://cloud.githubusercontent.com/assets/2317133/14457735/514b3576-00ca-11e6-9885-d800865dcc89.png)
