### ISSUE TITLE
 it should not always highlight the 1st skill

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#105]
Mac 10.11.4 + Chrome 49.0

1. open https://www.topcoder-qa.com/search/members/?q=math
2. scroll down , observe "PMath"

expected: it should not highlight “JavaScript”

actual: see screenshot

![qq20160409-42 2x](https://cloud.githubusercontent.com/assets/4590317/14402553/0dc9b0f8-fe6c-11e5-872c-6aec13909cc3.png)

**Comment by callmekatootie** [comment]
Not sure if bu @fnisen @nlitwin

**Comment by nlitwin** [comment]
I believe this bug has been logged already, where searching for skills sometimes shows the wrong first highlighted skill. (https://github.com/appirio-tech/topcoder-app-r/issues/26), although I'm not sure who is the first to log this bug.
