### ISSUE TITLE
page crash on search for special character

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/topcoder-app-r#106]
1. Launch the site
2. login with username: sweta.ipec pwd: sweta@123
3. go to searchbox
4. Enter search string as : ~@#$%^^&&*(){}|:"<>?
5. click on search 

![6](https://cloud.githubusercontent.com/assets/16131461/14402564/71f15140-fe57-11e5-9428-e5ab80470694.png)

![image](https://cloud.githubusercontent.com/assets/16131461/14402565/7e115402-fe57-11e5-968d-f95ddcf6f66a.png)

**Comment by callmekatootie** [comment]
Duplicate - has come before
