### ISSUE TITLE
The results are not displayed alphabetical order

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#108]
Environment

Chrome 47.0.2526.73
Mozilla Firefox 45.0.1
Safari 9

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Press on the search icon glass from the top right of page.

3) Set a text in search field as "C#".

actual: observe as results are not alphabetical ordered returned.

expected: display the results in alphabetical order.

see attach!

![results-not-ordered](https://cloud.githubusercontent.com/assets/18361424/14402580/e39253f4-fe42-11e5-9111-e75af453f0aa.png)

**Comment by callmekatootie** [comment]
They won't - they have a ranking depending on how relevant they are to the search query
