### ISSUE TITLE
Find Members placeholder text does not match style of page

### ISSUE THREAD

**Issue by Colinh84** [appirio-tech/topcoder-app-r#109]
The place holder text does not match the style of the text of the page or the input when you start typing your query. 

Steps:
- hover on search icon
- see that "FIND MEMBERS" text looks out of place and does not match font style when you start typing in input box or that of the rest of the site.

Expected:
- font styling should match the style of the input text when you start typing in field

Actual:
- font style is smaller, uppercase, and does not match any other font styling on page.

Screenshot: http://i.imgur.com/iklRUDP.png
**Requirements**
- [ ] Please adhere to the code style specified in the readme.
- [ ] Make sure the component is rendered correctly on all screen sizes as specified in the designs

**Comment by callmekatootie** [comment]
Not sure if bug @fnisen @nlitwin

**Comment by nlitwin** [comment]
Same as comment here: https://github.com/appirio-tech/topcoder-app-r/issues/107#issuecomment-209015975
