### ISSUE TITLE
TagList Enhancement

### ISSUE THREAD

**Issue by nlitwin** [appirio-tech/topcoder-app-r#11]
**Requirements**
- [ ] Please adhere to the code style specified in the readme.
- [ ] Add an enhancement to the `TagList` component to show the number of tags, which are currently not shown.
- [ ] Investigate whether using the `react-dotdotdot` library would be helpful, which is already being used elsewhere.
- [ ] Name the new prop `showEllipsis`, which is a Boolean `PropType`
- [ ] Enhancement should not break desktop or mobile experience of `TagList` on the member search page `http://localhost:3000/search/members?q=javascript`
- [ ] Make sure the component is rendered correctly on all screen sizes as specified in the designs

**Resources**
 - [Design specks](https://drive.google.com/open?id=0B1LbmKnex41fOWdBMHdGQU1jbTQ)

**Comment by vikasrohit** [comment]
Can we reuse TaggedValueList component here? It has the functionality of showing number of tags. We can modify it to be more generic, if required.

**Comment by nlitwin** [comment]
I think it might be possible to get it working for both cases, although I think the two components are different enough that it warrants separate components. TagList is for what we're calling tags in the DB (skills, events, countries, etc.), whereas TaggedValueList is closer to LabelIconGroup, which is text + some sort of icon.

**Comment by vikasrohit** [comment]
We can control show/hide of label of the tag for TaggedValue/TaggedValueList components so that we can use it as list of only tags.
