### ISSUE TITLE
Search after a skill is incorrect returned

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#110]
Environment

Chrome 47.0.2526.73

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Press on the search icon glass from the top right of page.

3) Set the skill=Math in search field.

4) Press enter to perform the action.

actual: users without Math are returned but which have the skill "Advanced Math".

expected: return only users with skill "Math".

see attach!

![math](https://cloud.githubusercontent.com/assets/18361424/14402623/0566752c-fe44-11e5-9cca-1c0830b80c6d.png)

**Comment by callmekatootie** [comment]
You can see that the person has "Math" in their skillset - if they have Advanced Math in their skillset, I would expect that they also have Math! Not a bug
