### ISSUE TITLE
Invalid users returned for a skill

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#112]
Environment

Chrome 47.0.2526.73

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Press on the search icon glass from the top right of page.

3) Set the skill "String parsing" in search field.

4) Press enter to perform the search action.

actual: users are returned even don't have set the "String parsing" skill.

expected: display only users with this skill.

see attach!

![user-without](https://cloud.githubusercontent.com/assets/18361424/14402644/a943bd08-fe44-11e5-8ce6-924f2e8a83d6.png)

**Comment by callmekatootie** [comment]
I don't even get that user in my search results:
![image](https://cloud.githubusercontent.com/assets/2317133/14481543/a9570ba0-0151-11e6-9b96-5369a2a5d6bf.png)

Invalid issue
