### ISSUE TITLE
End Result text is not visible if there are only 10 search results

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/topcoder-app-r#113]
1.1. Launch the site
2. login with username: sweta.ipec pwd: sweta@123
3. go to searchbox
4. enter data science as search string

Expected Result: text should visible
Actual Result: text not visible

![image](https://cloud.githubusercontent.com/assets/16131461/14402646/c2d6557c-fe59-11e5-9699-7b16b4328cdf.png)

**Comment by callmekatootie** [comment]
This is a duplicate issue and I have come across it earlier
