### ISSUE TITLE
Invalid users returned for a skill set

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#114]
Environment

Chrome 47.0.2526.73

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Press on the search icon glass from the top right of page.

3) Set in search field the skill "String Manipulation".

4) Press enter to perform the action.

actual: the user "albertwang" is returned even have no this skill set.

expected: display only users with this skill.

see attach!

![no-skill](https://cloud.githubusercontent.com/assets/18361424/14402663/273548ee-fe45-11e5-8416-0b87abdbdb73.png)

**Comment by callmekatootie** [comment]
I don't get him in my search results:
![image](https://cloud.githubusercontent.com/assets/2317133/14481578/fb06b5ea-0151-11e6-840c-9d9be9c774cd.png)

Invalid issue
