### ISSUE TITLE
[Common] 'Top Members in' won't show 'c#' as the search string

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#115]
Description
-----------------------------------------------------------------
[Common] 'Top Members in' won't show 'c#' as the search string

Steps
-----------------------------------------------------------------
- Open the Topcoder Search Web Page

- https://www.topcoder-qa.com/search/members/?q=c#

- Check the 'Top Members in XX' Title

- Search URL is become : https://www.topcoder-qa.com/search/members/?q=c

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- Must display as 'Top Members in C#'

Actual result
-----------------------------------------------------------------
'Top Members in' won't show 'c#' as the search string

Environment
-----------------------------------------------------------------
Chrome 49.0.2623.112 m, 
FF 45.0.1, 
IE 11
iPhone 6s, Safari
iPhone 5, Safari

Image/Video/JS Log
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![a](https://cloud.githubusercontent.com/assets/4592712/14407497/fba0ba16-fee8-11e5-9afc-915732965fee.png)

**Comment by callmekatootie** [comment]
Same as the ticket where searching for C++ shows C instead
