### ISSUE TITLE
The characters are not alligned in field

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#116]
Mozilla Firefox 45.0.1

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Press on the search icon glass from the top right of page.

3) Set in search field the text "html5".

actual: observe as the characters are not aligned.

expected: display the characters aligned.

see attach!

![text](https://cloud.githubusercontent.com/assets/18361424/14402696/e39e12c2-fe45-11e5-8515-1cc95e08fec1.png)
text.png

**Comment by callmekatootie** [comment]
That's the font used! Not a issue
