### ISSUE TITLE
[Common] Wrong Results displayed when we search 'C#' as the skill set

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#117]
Description
-----------------------------------------------------------------
[Common] Wrong Results displayed when we search 'C#' as the skill set

Steps
-----------------------------------------------------------------
- Open the Topcoder Search Web Page

- https://www.topcoder-qa.com/search/members/?q=c#

- Check the member list

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- Must display the correct users that have C# skill set

Actual result
-----------------------------------------------------------------
Wrong Results displayed when we search 'C#' as the skill set

Environment
-----------------------------------------------------------------
Chrome 49.0.2623.112 m, 
FF 45.0.1, 
IE 11
iPhone 6s, Safari
iPhone 5, Safari

Image/Video/JS Log
-----------------------------------------------------------------
![19](https://cloud.githubusercontent.com/assets/4592712/14402701/fc1701aa-fe5a-11e5-9a1b-a5309236400f.png)

**Comment by callmekatootie** [comment]
I am getting results for C instead, which was reported already in another ticket. I don't get the above results
