### ISSUE TITLE
[Common] No need to have (,) comma in rating values

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#118]
Description
-----------------------------------------------------------------
[Common] No need to have (,) comma in rating values

Steps
-----------------------------------------------------------------
- Open the Topcoder Search Web Page

- https://www.topcoder-qa.com/search/members/?q=c#

- Check the member list

- Check the rating values (2,089, 2,715)

- But in the profile page it display without the commas (https://www.topcoder-qa.com/members/nhzp339/)

- Must remove commas to be consistent with other locations

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- No need to have (,) comma in rating values

Actual result
-----------------------------------------------------------------
(,) comma displayed in rating values

Environment
-----------------------------------------------------------------
Chrome 49.0.2623.112 m, 
FF 45.0.1, 
IE 11
iPhone 6s, Safari
iPhone 5, Safari

Image/Video/JS Log
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![20 1](https://cloud.githubusercontent.com/assets/4592712/14402717/817c3c20-fe5b-11e5-9d3f-d79eea60747c.png)
![20 2](https://cloud.githubusercontent.com/assets/4592712/14402718/817da060-fe5b-11e5-94c7-4bb106385e0c.png)

**Comment by callmekatootie** [comment]
@fnisen @nlitwin Bug?

**Comment by nlitwin** [comment]
This one's not a bug, as commas were purposefully added.

**Comment by fnisen** [comment]
@nlitwin - let's allow this one. The stylistic inconsistency is a fair point.
