### ISSUE TITLE
The section is override be popup window

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#119]
Environment

Mozilla Firefox 45.0.1

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Press on the search icon glass from the top right of page.

3) Considering as example the user "MiG -29" available.

4) Press on DESIGNER text.

actual: the popup window override the bottom section.

expected: display correct the popup window.

see attach!

![override_001](https://cloud.githubusercontent.com/assets/18361424/14402726/9e7ac7ca-fe46-11e5-9a78-ab00ccf17dc8.png)

**Comment by callmekatootie** [comment]
Can't reproduce - 
![image](https://cloud.githubusercontent.com/assets/2317133/14481757/bcf20492-0153-11e6-9c9c-c12fce45f299.png)

**Comment by onetliviunicu** [comment]
I was able to simulate again this issue using Chrome 49.0.2623.112 m and I assign to you a screen shoot.Please verify again!
![designer](https://cloud.githubusercontent.com/assets/18361424/14489778/c5646d94-0177-11e6-9f75-64ac71b6339e.png)

**Comment by onetliviunicu** [comment]
I can simulate this issue every time!Can you please review again?

**Comment by callmekatootie** [comment]
@onetliviunicu I recollect you reporting similar issues for the LUMA project - I think your screen resolution is too small or your screen size is too small to be supported.

Can you let us know what your screen size and resolution are?

**Comment by onetliviunicu** [comment]
I have a device HTC One M9(http://www.htc.com/us/smartphones/htc-one-m9/) which have system operation Android 6.0, Resolution 1080 x 1920 pixels, Size 5.0 inches.

**Comment by onetliviunicu** [comment]
:) sorry this is for mobile device and the issue was logged for pc.My pc is this
http://www.cnet.com/products/hp-635-15-6-e-350-windows-7-home-premium-64-bit-2-gb-ram-320-gb-hdd-series/specs/

**Comment by callmekatootie** [comment]
Actually - that page was not in scope for the contest! :) Only the search page is. So, I can't take it as a bug, even if it is one

But I will bring it to the attention of the Topcoder team - @fnisen @nlitwin
