### ISSUE TITLE
ChallengePrizes

### ISSUE THREAD

**Issue by nlitwin** [appirio-tech/topcoder-app-r#12]
**Requirements**
- [ ] Please adhere to the code style specified in the readme.
- [ ] Implement the `ChallengePrizes` component in the`components/ChallengeCard/ChallengeInfoSecondary/ChallengePrizes` directory
- [ ] Make sure all permutations are handled, i.e. total prize money and number of prizes, prize money of taskpay, and just task pay. See designs for details.
- [ ] Make sure the component is rendered correctly on all screen sizes as specified in the designs

**Resources**
 - [Design specks](https://drive.google.com/open?id=0B1LbmKnex41fOWdBMHdGQU1jbTQ)

**Comment by vikasrohit** [comment]
May be we can reuse PrizeItem component here.

**Comment by nlitwin** [comment]
Hmm, now that I think of it, what about PrizeItem and ChallengePrizes both instances of TaggedValue?

**Comment by vikasrohit** [comment]
Exactly. I have that requirement in final fix for PrizeItem component. :grin:
