### ISSUE TITLE
Invalid results when search after specific skill

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#120]
Environment

Chrome 47.0.2526.73

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Press on the search icon glass from the top right of page.

3) Complete search field with text "Activity Diagrams".

4) Press enter to perform the search.

actual: the users without this skill are returned as example Standlove but which have the skill as Active Directory.

expected: display only users with the set skill(only Activity Diagrams skills).

see atatch!

![user-activity](https://cloud.githubusercontent.com/assets/18361424/14402796/0d5c007c-fe48-11e5-9f66-eae18c8470d2.png)

**Comment by callmekatootie** [comment]
I don't get that user in my results
