### ISSUE TITLE
[Common] Profile image shirked 

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#121]
Description
-----------------------------------------------------------------
[Common] Profile image shirked 

Steps
-----------------------------------------------------------------
- Open the Topcoder Search Web Page

- https://www.topcoder-qa.com/search/members/?q=photoshop

- Check the 'iamtong' profile

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- Must display the profile picture properly

Actual result
-----------------------------------------------------------------
- Profile image shirked

Environment
-----------------------------------------------------------------
iPhone 5, Safari

Image/Video/JS Log
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![4](https://cloud.githubusercontent.com/assets/4592712/14407518/341d3da0-feea-11e5-9df3-dfd259386026.PNG)

**Comment by callmekatootie** [comment]
Appears fine for me

![image](https://cloud.githubusercontent.com/assets/2317133/14481805/2420a560-0154-11e6-8215-7ea72f5a36ed.png)
