### ISSUE TITLE
Invalid results when search after specific skill Google Api

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#122]
Environment

Chrome 47.0.2526.73

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Complete search field with an existing skill as "Google Api".

4) Press enter to perform the action.

actual: users without this skill are returned as example "Standlove".

expected: return only users with the skill set.

see attach!

![google-api](https://cloud.githubusercontent.com/assets/18361424/14402827/f781a490-fe48-11e5-8d59-799c976158fb.png)

**Comment by callmekatootie** [comment]
Can't reproduce: 
![image](https://cloud.githubusercontent.com/assets/2317133/14481819/453ea0ee-0154-11e6-9cab-a38305b9e0b1.png)
