### ISSUE TITLE
Users without skill set are returned

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#123]
Environment

Chrome 47.0.2526.73

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Complete search field with text "Java".

4) Use load more option to load all users.

actual: the user "wahjava" is returned even the skill is not set.

expected: display only users with this skill.

see attach!

![no-skill_001](https://cloud.githubusercontent.com/assets/18361424/14402848/aae7f480-fe49-11e5-94ab-48bd891994b5.png)

**Comment by callmekatootie** [comment]
That is the User's matching "java" section - wahjava contains the string java and hence it has been returned.
