### ISSUE TITLE
Invalid users returned for a skill which was set

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#125]
Environment

Chrome 47.0.2526.73

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Complete search field with text "IBM Websphere…".

4) Press enter to perform the action.

actual: the user Standlove is returned even not have this skill set.

expected: return only users with this skill set.

see attach!

**Comment by callmekatootie** [comment]
![image](https://cloud.githubusercontent.com/assets/2317133/14481925/013b47ac-0155-11e6-998f-a71e407c77d1.png)
