### ISSUE TITLE
Set a minim two characters for searching

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#126]
Environment

Chrome 47.0.2526.73

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Complete search field with "C" as example.

4) Press enter to perform the operation.

actual: results are returned.

expected: do not allow searching after one character set a minim of two

**Comment by onetliviunicu** [comment]
For special cases as "C" skill allow the search to be performed but with other not!

**Comment by callmekatootie** [comment]
Why? What about 2 letter usernames?

**Comment by onetliviunicu** [comment]
No, you don't understand.Evey search field must have a minimum of characters for which is performed the searching.Multiple tutorials and best practices said about this.Why I wanted with this issue is to set a minimum of 2,3 characters depending of how you many you want to be and these to must be required to be entered by users.The "C" can be a special case when the user search this programming language but I think the others letter are not used.So perform the searching after "C" if is entered by user BUT not allow other search operation for one single letter.
Thank you!

**Comment by callmekatootie** [comment]
I meant there can be two letter usernames. They need to be searchable isn't it? If we set a minimum limit on the number of characters to search with we cannot search for these users at all then

**Comment by onetliviunicu** [comment]
Please tell me in which case do you use searching for a single character as example "A", "B"...?

**Comment by callmekatootie** [comment]
There is a language called B, D, R, F*

Also - I think usernames are possible. It's not just the skillset
