### ISSUE TITLE
Number of results is incorrect

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#127]
Environment

Chrome 47.0.2526.73

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Complete search field with "Javascript".

actual: only 10 results are displayed.

expected: return correct number of users and display Load More option.

see attach!

![javascript](https://cloud.githubusercontent.com/assets/18361424/14402955/cc1b1012-fe4c-11e5-9b66-a9c5e9f88c3b.png)

**Comment by callmekatootie** [comment]
To members will always be up to 10 - its the usernames matching the query that have infinite scroll
