### ISSUE TITLE
List is displayed for a short period of time

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#128]
Environment

Chrome 47.0.2526.73

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Complete an invalid text in search field "Yii/".

4) Press enter to perform the action.

actual: for a short period of time the page is displayed even no results.

expected: display the error page.

see attach!

Notes

The video from attachments is in zip format required to be uploaded!Unzip the file!

[yii.zip](https://github.com/appirio-tech/topcoder-app-r/files/211157/yii.zip)

**Comment by callmekatootie** [comment]
There is already a ticket for invalid characters in search strings.

There is also a ticket about showing the page briefly and then showing no results - and that was closed too because that is how the page behavesB
