### ISSUE TITLE
Skills are not correct set in section

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#129]
Android 6.0
HTC One M9
Chrome

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Search after "nhzp339".

4) Press enter to perform the action.

5) Press on the user to see the profile.

6) Go to Skills section.

actual: skills are not displayed ordered in section(3,3,1).

expected:display three available skills on the line.

see attach!

![skills](https://cloud.githubusercontent.com/assets/18361424/14403084/be0eb5ae-fe52-11e5-9bdd-f24cd733145d.png)

**Comment by callmekatootie** [comment]
skillset page is not in scope - only search is
