### ISSUE TITLE
Display correct number of skills in section

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#130]
Environment

Chrome 47.0.2526.73
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) In search field set an existing user as example "ainu7".

4) Press enter to perform the search.

5) Press on the username to redirect in profile section.

- Observe as 6 skills are displayed on the first line and the next 4 skills on the second line.

6) Press View All button.

- Observe another two skills are set on the second line and on the third line are displayed 4 skills.

expected: display two lines with three skills and when the View All button is pressed display another four skills on the new line.

see attach!

![one](https://cloud.githubusercontent.com/assets/18361424/14403108/bfd264f2-fe53-11e5-98de-479a36351181.png)
![two](https://cloud.githubusercontent.com/assets/18361424/14403109/c45c23d2-fe53-11e5-89a9-04cbd0fa8955.png)

**Comment by callmekatootie** [comment]
that page is not in scope for this contest
