### ISSUE TITLE
should display numbers for results in the 2nd section

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#131]
Mac 10.11.4 + Chrome 49.0

1. open https://www.topcoder-qa.com/search/members/?q=math
2. scroll down, observe

expected: should display numbers on each result row in the 2nd section, just like in the 1st section.

actual: see screenshot

![qq20160409-59 2x](https://cloud.githubusercontent.com/assets/4590317/14403131/54b30192-fe7e-11e5-9bb8-871b024bde36.png)

**Comment by callmekatootie** [comment]
I think the second section has no ranking or rather can show more than 10 results. Best not to have numbers in such a case as the list doesn't end for some search strings
