### ISSUE TITLE
Text is overwritten when is selected

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#132]
Environment

Chrome 47.0.2526.73
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Complete search field with text "nhzp339".

4) Press enter to perform the search operation.

5) Press on the user name to redirect into profile section.

6) Select the Activity Diagram skill.

actual: observe as the text is overwritten.

expected: do not overwritten text.

see attach!

![overwrittem](https://cloud.githubusercontent.com/assets/18361424/14403132/78bafd76-fe54-11e5-89d5-90470484aa0a.png)

**Comment by callmekatootie** [comment]
Skill set page not in scope
