### ISSUE TITLE
The same parameter is parsed in url 

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#133]
Environment

Mozilla Firefox 45.0.1

Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Complete search field with "C".

4) Press enter.

Observe the link https://www.topcoder-qa.com/search/members/?q=C with q parameter equal with C.

5) Select again the search field.

6) Set in field "C++" and press enter.

Observe the same parameter is parsed.

expected: set the correct parameter in URL.

see attach!

[vide-search.zip](https://github.com/appirio-tech/topcoder-app-r/files/211174/vide-search.zip)
vide-search.swf

Notes

- Using Chrome web browser this link is generated https://www.topcoder-qa.com/search/members/?q=C%20%20

- I uploaded an archived zip with file because only this is allowed, please unzip to see the video!

**Comment by callmekatootie** [comment]
Duplicate - raised before

**Comment by onetliviunicu** [comment]
Can you please set a comment with duplicated issues?
Thank you!

**Comment by callmekatootie** [comment]
Duplicate of - https://github.com/appirio-tech/topcoder-app-r/issues/53
