### ISSUE TITLE
Invalid results for skill set

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#134]
Mozilla Firefox 45.0.1
Chrome 47.0.2526.73

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Complete search field with text "C#".

4) Press enter to perform the action.

actual: observe the URL link and q parameter (https://www.topcoder-qa.com/search/members/?q=C).

expected: the search must be peformed correct.

**Comment by callmekatootie** [comment]
Duplicate - raised before
