### ISSUE TITLE
Users stats are displayed cut in screen

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#137]
Android 6.0
HTC One M9
Chrome

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Into search field set "Commerce" text.

4) Press enter to perform the search action.

actual: the stats of users are displayed cut.

expected: display correct stats of users.

see attach!

![stats](https://cloud.githubusercontent.com/assets/18361424/14403208/2b935702-fe57-11e5-9a65-06ef455b02ce.png)

**Comment by callmekatootie** [comment]
There do seem to be issues with it:

![image](https://cloud.githubusercontent.com/assets/2317133/14482360/92f771c6-0159-11e6-83e1-7fa67752b880.png)

**Comment by nlitwin** [comment]
This is working as expected. It's a horizontal scroll for mobile, which is indicated by the fact that it's hanging off the screen. We are discussing internally whether we want to prevent desktop users from seeing this, who will have trouble scrolling horizontally.

**Comment by onetliviunicu** [comment]
hy, I don't understand, exactly in this way is displayed on my device for testing HTC One M9.Please see attachment!There the image is displayed cut on the right side.There is not any horizontally scroll bar to be used.Please verify again this issue and see the screen shoot!
![image-cut](https://cloud.githubusercontent.com/assets/18361424/14500286/1e0c3f76-01aa-11e6-9daf-cc5049a31f7d.png)

**Comment by nlitwin** [comment]
Hmm, if you're saying that this is an actual phone being tested and the horizontal scroll feature is not working, then we can take it as a bug. Although I'm not sure how to verify it

**Comment by callmekatootie** [comment]
browserstack.com ?

**Comment by nlitwin** [comment]
I think we need to buy a plan in order to test that device.

**Comment by callmekatootie** [comment]
Yep. It has a 30 min free version though.

**Comment by nlitwin** [comment]
I am able to access the free tier, but can't find the 30 min free version for the paid tier. Although I tested on a Motorola and Google Nexus 6 phone and the horizontal scroll is working.

**Comment by onetliviunicu** [comment]
Even on Motorola and Google Nexis 6 works correct, on my device is displayed as is in screen shoot.If you don't have this device for testing accept this issue to be resolved.I don't have any reason to lie you as is not a bug or is not displayed in this way on my device!
Thank you!

**Comment by nlitwin** [comment]
@callmekatootie Is it too late to mark this as a bug?

**Comment by callmekatootie** [comment]
I think we can
