### ISSUE TITLE
[Common] When Loading extra; Loading animation must display

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#138]
Description
-----------------------------------------------------------------
[Common] When Loading extra; Loading animation must display

Steps
-----------------------------------------------------------------
- Open the Topcoder Search Web Page

- https://www.topcoder-qa.com/search/members/?q=sim

- Click Load more

- Scroll down; and see

- New items loaded but loading animation is not displayed

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- When Loading extra; Loading animation must display
- If not user may think there are no extra items to load

Actual result
-----------------------------------------------------------------
- When Loading extra; Loading animation is not display

Environment
-----------------------------------------------------------------
Chrome 49.0.2623.112 m, 
FF 45.0.1, 
IE 11
iPhone 6s, Safari
iPhone 5, Safari

Image/Video/JS Log
-----------------------------------------------------------------

**Comment by sdgun** [comment]
http://www.screencast.com/t/Hc1Zspfq8

**Comment by callmekatootie** [comment]
It's infinite scroll - there isn't expected to be one animation here.
