### ISSUE TITLE
No clear field option available

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#139]
Android 6.0
HTC One M9

1) Access application link https://www.topcoder-qa.com/search/members/.
2) Go to menu section.
3) Set any text in search field.

actual: no clear field option available.
expected: add clear all option.

see attach!

![clear-all](https://cloud.githubusercontent.com/assets/18361424/14403263/58de9c60-fe59-11e5-90af-24ea0b6a06b0.png)

**Comment by callmekatootie** [comment]
Duplicate issue - has been reported before

**Comment by onetliviunicu** [comment]
Please set a comment with duplicated issue!

**Comment by callmekatootie** [comment]
Duplicate of https://github.com/appirio-tech/topcoder-app-r/issues/77
