### ISSUE TITLE
text on the result row is not selectable

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#140]
Mac 10.11.4 + FF45.0.1

1. open https://www.topcoder-qa.com/search/members/?q=j2ee
2. try to select “argolite” on the first row

expected: it should allow the user to select the text on the result row, so that they can copy/paste.

actual: see screenshot, it does not allow the user to select any text.

![qq20160409-64 2x](https://cloud.githubusercontent.com/assets/4590317/14403378/b5db83b0-fe86-11e5-8581-1a4e160292e1.png)

**Comment by callmekatootie** [comment]
@fnisen @nlitwin I don't expect a selection to happen but checking with you if it should

**Comment by nlitwin** [comment]
I believe this is part of the tradeoff we made by making the entire member item clickable. @fnisen ?

**Comment by fnisen** [comment]
@nlitwin - yes, agree.
