### ISSUE TITLE
Default image as avatar is not displayed

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#141]
Environment

Mozilla Firefox 45.0.1
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Complete the field with the name of existing user without image set(ex: hmig).

4) Press enter to perform the search icon.
 
5) Press on the user name to redirect into profile section.

actual: no default image set for the users without profile picture.
expected: set a default image for users to be displayed.

see attach!

![default-avatar](https://cloud.githubusercontent.com/assets/18361424/14403381/e0a893f0-fe5c-11e5-88db-e16b23375aff.png)

**Comment by callmekatootie** [comment]
That page is not in scope for the contest
