### ISSUE TITLE
Invalid avatar picure is displayed

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#142]
Chrome 47.0.2526.73
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Search an existing user without avatar picture image uploaded(ex: hmig).

4) Press enter to perform the action.

5) Press on the user name to redirect into profile page.

actual: invalid avatar image is displayed.
expected: display the default image for this case.

see attach!
![invalid-avatar](https://cloud.githubusercontent.com/assets/18361424/14403397/6dc90daa-fe5d-11e5-9813-454d8476fb37.png)

**Comment by callmekatootie** [comment]
Page not in scope
