### ISSUE TITLE
Letters from username is displayed cut

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#143]
Environment

Chrome 47.0.2526.73
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Set text "galeassim" and press enter.

actual: "g" letter is displayed cut.
expected: full display the letters of username word.

see attach!

![g-letter](https://cloud.githubusercontent.com/assets/18361424/14403427/5c322166-fe5e-11e5-8d42-6a34baa06566.png)

**Comment by callmekatootie** [comment]
Duplicate issue. Reported before - with character "g" only actually!
