### ISSUE TITLE
[Common] No need to display '#' for Skill set

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#144]
Description
-----------------------------------------------------------------
[Common] No need to display '#' for Skill set

Steps
-----------------------------------------------------------------
- Open the Topcoder Search Web Page

- https://www.topcoder-qa.com/search/members/?q=sim

- Check the Skills list

- It has '#' in-front of the skill name

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- Must remove # from the skill list

Actual result
-----------------------------------------------------------------
- No need to display '#' for Skill set

Environment
-----------------------------------------------------------------
Chrome 49.0.2623.112 m, 
FF 45.0.1, 
IE 11
iPhone 6s, Safari
iPhone 5, Safari

Image/Video/JS Log
-----------------------------------------------------------------
![23](https://cloud.githubusercontent.com/assets/4592712/14403518/28210bee-fe77-11e5-8844-4b73b0cb9534.png)

**Comment by callmekatootie** [comment]
eh? why shouldn't it display it that way? It's a tag / twitter hash tag type display
