### ISSUE TITLE
Existing skill which begin with lowercase

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#145]
Environment

Chrome 47.0.2526.73
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Complete search field with "bower".

4) Press enter to perform the search.

actual: the users are returned.

expected: change the name of skill to begin with uppercase because is the only skill in this format.

see attach!

![bower](https://cloud.githubusercontent.com/assets/18361424/14403545/9f51c30c-fe63-11e5-845a-a949352855c1.png)

**Comment by callmekatootie** [comment]
page not in scope
