### ISSUE TITLE
User returned even no skills added

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#146]
Environment

Chrome 47.0.2526.73
Mozilla Firefox 45.0.1
Windows 7

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Complete search field with text "Unit-Testing".

4) Press enter to perform the search operation.

5) Press on the name of existing returned user as example DhananjayKumar1.

actual: in profile page the skills are not available and the user was returned for this search text.

expected: return only users which match!

see attach!

[unit-testing.zip](https://github.com/appirio-tech/topcoder-app-r/files/211205/unit-testing.zip)

**Comment by onetliviunicu** [comment]
Notes

- the video file was set in a archive zip, please unzip to see the video!

**Comment by callmekatootie** [comment]
I'll accept this. Seems like the user is shown to have that skill set in the search result but the profile page indicates none:

![image](https://cloud.githubusercontent.com/assets/2317133/14482446/7dbc87fa-015a-11e6-9cae-a27dd60457a1.png)

![image](https://cloud.githubusercontent.com/assets/2317133/14482448/875a0fbc-015a-11e6-9138-78d4908181f8.png)

**Comment by nlitwin** [comment]
Tracking in Asana: https://app.asana.com/0/95457970819732/114044849026593
