### ISSUE TITLE
[Common] Difficult to focus on the search text filed

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#147]
Description
-----------------------------------------------------------------
[Common] Difficult to focus on the search text filed

Steps
-----------------------------------------------------------------
- Open the Topcoder Search Web Page

- Try to hover over the search icon and type a search term

- Sometimes when the focus is lost search drop down hides; so it must be static; after search it can be hidden.

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- Must not collapse when we focus on another location
- When user click on the search icon it will open the text field and when we click on it again then it will close the search drop down

Actual result
-----------------------------------------------------------------
- Difficult to focus on the search text filed

Environment
-----------------------------------------------------------------
Chrome 49.0.2623.112 m, 
FF 45.0.1, 

Image/Video/JS Log
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![1c](https://cloud.githubusercontent.com/assets/4592712/14416229/35563100-ffc5-11e5-8dce-f82ffec75ef4.png)

**Comment by callmekatootie** [comment]
Can't make out what the issue is. Needs a video or more description
