### ISSUE TITLE
When back the vertical scroll bar position is kept to the top

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#148]
Android 6.0
HTC One M9

Description

-------------------------------------------------------------------------------------------------------------

1) Access application link https://www.topcoder-qa.com/search/members/.

2) Go to main menu.

3) Complete search field with "Design" text.

4) Press enter to perform the search action.

5) Press Load More button.

6) Scroll to the bottom of page until multiple results are loaded.

7) From the results press on the username as example "designbyheart".

8) From profile section use "back" device option.

actual: redirect to previous page with vertical scroll bar position set to the top of page.

expected: keep the vertical scroll bar position fixed(near the user designbyheart).

see attach!

![one](https://cloud.githubusercontent.com/assets/18361424/14404299/f08c7fd4-fe7a-11e5-9cdc-f65880561d03.png)
![two](https://cloud.githubusercontent.com/assets/18361424/14404300/f60d9b96-fe7a-11e5-8162-0fe04c5cdbf5.png)

**Comment by callmekatootie** [comment]
@fnisen @nlitwin Bug? Basically, if the user scrolls to the bottom and then views a profile - and finally comes back to the search results page, the earlier scrolled position is lost.

I think this is common because of the infinite scroll feature but just checking if you would take this as a bug

**Comment by nlitwin** [comment]
I don't view this as a bug. It's a feature that we didn't build. @fnisen ?

**Comment by fnisen** [comment]
@nlitwin - let's allow. I think it's a reasonable expectation.
