### ISSUE TITLE
When use back button browser keep the data loaded

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#149]
Environment

Chrome 49.0.2623.112
Mozilla Firefox 45.0.1
Windows 7

Description

---------------------------------------------------------------------------------------------------------

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Complete search field with text "Design".

4) Press enter to perform the search operation.

5) Go to the bottom of page and press Load More button.

6) Use vertical scroll bar to the bottom of page.

7) Press on existing username "designbyheart".

8) From profile page use back button browser.

actual: redirect to search results page and vertical scroll bar position is set to the top.

expected: keep the vertical scroll bar position fixed.

see attachment!

![design](https://cloud.githubusercontent.com/assets/18361424/14404335/b2839df2-fe7b-11e5-8200-333881b689f3.png)

**Comment by callmekatootie** [comment]
You raised this in #148 as well

**Comment by onetliviunicu** [comment]
hy, I don't know why you consider the same issue if the same bug is founded on mobile and desktop.On mobile devices is a test which is performed and on desktop is another test.Even the same issues are existing on both can not be counted as one because are different!
Please review again this issue!

**Comment by callmekatootie** [comment]
I am sorry but I can't consider same issue in different devices - as I said, every participant could simply post their issue twice - once in mobile and one in desktop. It would be a disaster if that was acceptable.

Duplicate issues are not allowed.
