### ISSUE TITLE
[Common] Issue in the location of some ranking icons in the Profile image

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#150]
Description
-----------------------------------------------------------------
[Common] Issue in the location of some ranking icons in the Profile image

Steps
-----------------------------------------------------------------
- Open the Topcoder Search Web Page

- https://www.topcoder-qa.com/search/members/?q=web%20site

- Check the Ranking icon position

- Check 1-6 (display with in the profile image)

- Check 7-9 (Display outside the Profile image)

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- Must display in the same location

Actual result
-----------------------------------------------------------------
- Issue in the location of some ranking icons in the Profile image

Environment
-----------------------------------------------------------------
Samsung Galaxy S5, Android 5.0

Image/Video/JS Log
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![1d1](https://cloud.githubusercontent.com/assets/4592712/14416269/96fbaa5c-ffc5-11e5-83f3-0d1a89fcc8a1.png)
![1d2](https://cloud.githubusercontent.com/assets/4592712/14416271/9726714c-ffc5-11e5-9d20-971c294b84f1.png)

**Comment by callmekatootie** [comment]
It's partially on and off the image in each case. Dont see the issue here
