### ISSUE TITLE
[Common] 'web site' and 'web sites' returns different search results

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#151]
Description
-----------------------------------------------------------------
[Common] 'web site' and 'web sites' returns different search results

Steps
-----------------------------------------------------------------
- Open the Topcoder Search Web Page

- https://www.topcoder-qa.com/search/members/?q=web%20site

- Check the Search list --> Web Services

- https://www.topcoder-qa.com/search/members/?q=web%20sites

- Check the Search list --> Force.Com Sites

- First instance is acceptable but the 2nd instance is totally different

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- Must display the relevant info

Actual result
-----------------------------------------------------------------
- 'web site' and 'web sites' returns different search results

Environment
-----------------------------------------------------------------
Chrome 49.0.2623.112 m, 
FF 45.0.1, 
IE 11
iPhone 6s, Safari
iPhone 5, Safari
Samsung Galaxy S5, Android 5.0

Image/Video/JS Log
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![26](https://cloud.githubusercontent.com/assets/4592712/14404389/3bedc926-fe92-11e5-8bc3-36f38ab6b247.png)

**Comment by callmekatootie** [comment]
Does behave weirdly - I guess the Force.com is because of the "sites" text in Force.com sites.

@fnisen @nlitwin Bug?

**Comment by nlitwin** [comment]
This is a bug. The leaderboard shouldn't even appear for search terms "web site" and "web sites"
