### ISSUE TITLE
 Search for hyperlinks can not be performed

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#152]
Environment

Chrome 49.0.2623.112
Windows 7

--------------------------------------------------------------------------------------------

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Considering an existing link of a member as example https://www.topcoder-qa.com/members/albertwang/.

4) Copy into clipboard this link and Paste into search field.

5) Press enter to perform the search operation.

actual: the page with no results is displayed.

expected:  search for hyperlinks should be performed.

see attach!

![hiperlink](https://cloud.githubusercontent.com/assets/18361424/14404432/da600cae-fe7e-11e5-99c2-c1ed11b9b7ed.png)

**Comment by callmekatootie** [comment]
You are searching a URL! of course nothing will be displayed

**Comment by onetliviunicu** [comment]
Why if I search an url nothing must be displayed?Maybe some users want to find the profile of user in topcoder and know just the url.Can you please review again?

**Comment by callmekatootie** [comment]
You misunderstand me. Actually, I did not write a correct response.

You searched for a URL - The app did not find any member or skillset for that URL. And hence as you can see, you get the response - NO results found.
