### ISSUE TITLE
[Common] 'force.com' display wrong results

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#153]
Description
-----------------------------------------------------------------
[Common] 'force.com' display wrong results

Steps
-----------------------------------------------------------------
- Open the Topcoder Search Web Page

- https://www.topcoder-qa.com/search/members/?q=force.com

- Check the Search list

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- Must display the records with the skill set 'force.com', I can see only one

Actual result
-----------------------------------------------------------------
- 'force.com' display wrong results

Environment
-----------------------------------------------------------------
Chrome 49.0.2623.112 m, 
FF 45.0.1, 
iPhone 6s, Safari
iPhone 5, Safari
Samsung Galaxy S5, Android 5.0

Image/Video/JS Log
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![27](https://cloud.githubusercontent.com/assets/4592712/14404438/1d94f89e-fe94-11e5-919f-025b1b859c4d.png)

**Comment by callmekatootie** [comment]
can't reproduce. Also, seems to be similar to the special character searches in other tickets
