### ISSUE TITLE
Users without any activity are listed in results

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#154]
Mozilla Firefox 45.0.1
Chrome 49.0.2623.112
Windows 7

--------------------------------------------------------------------------------------
Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Set the text "Design" in search field and press enter.

4) Use vertical scroll bar to the bottom of page.

actual: users available as example designcarnivore, aleksandardesign, ... are displayed even not have have at least one of the following: Avatar, Skills added, About Me / Bio added, Any competition activity (challenge or SRM).

expected:  To show up in username results listings, a user must have activated their account and have at least one of the following:
- Avatar
- Skills added
- About Me / Bio added
- Any competition activity (challenge or SRM)

![one](https://cloud.githubusercontent.com/assets/18361424/14404486/40d9d568-fe80-11e5-9c71-611647fd4e34.png)

![two](https://cloud.githubusercontent.com/assets/18361424/14404489/4813b5f6-fe80-11e5-9384-7389b9e7acd7.png)

**Comment by callmekatootie** [comment]
@fnisen @nlitwin Bug? I think they had some activity but they didn't win and hence they showed up?

**Comment by nlitwin** [comment]
I believe this is the same issue as the known bug, which is that some users have broken gravatar photoURLs.
