### ISSUE TITLE
Increase border margin for profile image section

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#155]
Chrome 49.0.2623.112
Mozilla Firefox 45.0.1
Windows 7

-----------------------------------------------------------------------------------------------------------------------

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Perform a search for "Design" letter.

4) Press on any existing user returned as example "dileepa".

actual: the left border margin seems to be invisible.

expected: increase the left border margin for section.

see attach!

![border-margin](https://cloud.githubusercontent.com/assets/18361424/14404515/0da462d4-fe81-11e5-824e-20392765c820.png)

**Comment by callmekatootie** [comment]
page not in scope
