### ISSUE TITLE
Ignore blank spaces in search parameter

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#156]
Mozilla Firefox 45.0.1
Chrome 49.0.2623.112
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Considering an existing user as example "deelepa" set in search field the text "di lee pa".

4) Press enter to perform the searching.

actual: the user can not be found.

expected: return the profile page of dileepa user.

see attach!

![search](https://cloud.githubusercontent.com/assets/18361424/14404537/c5a57ca6-fe81-11e5-9558-7ca769ff8800.png)

**Comment by callmekatootie** [comment]
Duplicate and seems to be the most common bug raised so far!
