### ISSUE TITLE
Ignore blank spaces in search parameter for users

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#157]
Environment

Mozilla Firefox 45.0.1
Chrome 49.0.2623.112
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Considering an existing username dileepa123.

4) Complete search field with text "dileep a123".

5) Press enter to perform the searching.

actual: no results found.

expected: ignore blank spaces and return the correct username.

see attach!

![dileepa](https://cloud.githubusercontent.com/assets/18361424/14404561/79d6d404-fe82-11e5-88c2-0ed4a8d16b33.png)

**Comment by callmekatootie** [comment]
Why should it do that? You can search for "web sites" and "Unit Testing" - multiple words

**Comment by onetliviunicu** [comment]
hy, as you can see in forum you write this 
- searching for two or more skills (e.g., Java and Python) is not supported.
Now you give an example for this issue with two words which is not correct.Can you please tell me if the issue is valid?

**Comment by nlitwin** [comment]
We never intended the search to work in this way. There is an initial check to see if the search term is a skill (even if it's two words) and then it looks for usernames matching the exact search term as it was given.
