### ISSUE TITLE
No back to top option available

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#158]
Android 6.0
HTC One M9
Chrome

-----------------------------------------------------------------

1) Access application link page https://www.topcoder-qa.com/search/members/?q=javascript.

2) Go to main menu.

3) In search field set the work "Api".

4) Press enter to perform the searching.

5) Use vertical scroll bar and go to the bottom of page.

6) Press "Load More" button.

7) Go to the bottom of page until "End of results" text is displayed.

----------------------------------------------------------------------------------------------------

actual: no "go to top" option available.

expected: display "go to top" option.

see attach!

![go-to-top](https://cloud.githubusercontent.com/assets/18361424/14404661/df54aec6-fe84-11e5-8ac2-8d0aeee72d10.png)
go-to-top.png

**Comment by callmekatootie** [comment]
@fnisen @nlitwin Bug or rather a feature you interested in providing?

**Comment by nlitwin** [comment]
I think that's a feature we didn't discuss building. @fnisen ?

**Comment by fnisen** [comment]
@nlitwin - yes, agree; it's a feature request.
