### ISSUE TITLE
Load More button lenght is as well as the section

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#159]
Environment

Mozilla Firefox 45.0.1
Chrome 49.0.2623.112
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Complete search field with word "Api".

4) Press enter to perform the searching.

5) Use vertical scroll bar to the top until Load More button is displayed.

actual: the length size of Load More button is the same as the section.

expected: set a lower length for Load More button and display centered.

see attach!

![load-more](https://cloud.githubusercontent.com/assets/18361424/14404690/5a3746da-fe85-11e5-9109-760d5ef8ba5d.png)

**Comment by callmekatootie** [comment]
Not a valid issue.

**Comment by callmekatootie** [comment]
I don't see anything wrong with it
