### ISSUE TITLE
Number 10 is too close to the profile image in Mobile

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#160]
Description
-----------------------------------------------------------------
Number 10 is too close to the profile image in Mobile

Steps
-----------------------------------------------------------------
- Open the Topcoder Search Web Page

- https://www.topcoder-qa.com/search/members/?q=php

- Scroll down and check the number 10

- Number 10 is too close to the profile image in Mobile

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- Middle point of the Number 10 must align with the number 9

Actual result
-----------------------------------------------------------------
- Number 10 is too close to the profile image in Mobile

Environment
-----------------------------------------------------------------
iPhone 6s, Safari
iPhone 5, Safari
Samsung Galaxy S5, Android 5.0

Image/Video/JS Log
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![17](https://cloud.githubusercontent.com/assets/4592712/14407495/cbf70a0e-fee8-11e5-8df0-59df13a5716d.png)

**Comment by callmekatootie** [comment]
Seems to be fine:

![image](https://cloud.githubusercontent.com/assets/2317133/14482762/c8ebc2ba-015d-11e6-8eb8-894e1ba89700.png)
