### ISSUE TITLE
Android - No max number of characters set  in fields

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#162]
Environment
Android 6.0
HTC One M9

----------------------------------------------------------

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Set a long characters in field.

actual: any long characters can be set in search field.

expected: allow a max number of characters.

see attach!

![max](https://cloud.githubusercontent.com/assets/18361424/14405213/520bb466-fe92-11e5-8776-e226ef1e04f7.png)

**Comment by callmekatootie** [comment]
Duplicate issue
