### ISSUE TITLE
Blank page when the search can not be performed

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#163]
Android 6.0
HTC One M9
Chrome

-------------------------------------------------------------------------------

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Go to main section.

4) In Search field add a long characters word(ex: abscjhajshajh235472@#$@#$23423jhsjuhsf...).

5) Press enter.

actual: blank page is returned.
expected: display the error page.

see attach!

![blank-page](https://cloud.githubusercontent.com/assets/18361424/14405242/10f851ea-fe93-11e5-9673-763f66771fa1.png)

**Comment by callmekatootie** [comment]
Appears fine for me

![image](https://cloud.githubusercontent.com/assets/2317133/14482809/4f3beeb2-015e-11e6-80c3-eff04c3df9d6.png)

**Comment by onetliviunicu** [comment]
For me not appears correct!The same message is displayed.Can you please verify again?

**Comment by callmekatootie** [comment]
@fnisen @nlitwin Can you check if you can reproduce this issue? I can't seem to

**Comment by onetliviunicu** [comment]
You can as example to add another some characters where is ... please use as example abscjhajshajh235472@#$@#$23423jhsjuhsfwerlkelrksdl;kfl;sdkfl;kdfl.
The scope with this issue is to see as in some cases the blank page is returned instead a page with the message.

**Comment by callmekatootie** [comment]
Note that you have used special characters in your search - that could be the cause of it - and this could be a duplicate issue of not handling special characters

**Comment by fnisen** [comment]
I also get a "no results found" page; special characters are likely the problem.

**Comment by onetliviunicu** [comment]
ok, I don't have any else way to explain as in a specific case the blank page is returned instead 'No results...' which is usually displayed for special chars.
Thank you!
