### ISSUE TITLE
Android - the loading users section is displayed

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#164]
Android 6.0
HTC One M9
Chrome

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Go to main menu section.

4) Set the word "Design" and press enter to perform the searching.

---------------------------------------------------------------------------------------------------

actual: the loading users section is displayed with blank sections before the users to be loaded.

expected: display only the message "Loading users" without the sections.

see attach!

![loading-users](https://cloud.githubusercontent.com/assets/18361424/14405269/aba0e252-fe93-11e5-8933-b7165d0f78a7.png)
loading-users.png

**Comment by callmekatootie** [comment]
Not a bug, its a feature ;)
