### ISSUE TITLE
Invalid search results returned

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#165]
Environment

Mozilla Firefox 45.0.1
Chrome 49.0.2623.112
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Complete search field with text "C----".

Observer as results as multiple data are returned!

Additional case

1) Search word "dileepa".

Observe two users returned.

2) Search word "dileepa123".

Observe one user returned.

expected: for word ""C----" return the error page with no results!

see attach!

![results-c----](https://cloud.githubusercontent.com/assets/18361424/14405371/3ffbc2f8-fe96-11e5-92e8-903ef7fc5801.png)
results-c----.png

**Comment by callmekatootie** [comment]
Seems to be same as the issue where C++ uses C as the query instead of C++
