### ISSUE TITLE
Android - skills are displayed cut

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#166]
Android 6.0
HTC One M9
Chrome

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Go to main menu.

3) Complete search field with text "Vijay123".

4) Press enter to perform the search.

actual: observe the skills for the users as are displayed cut.

expected: display correct the skills in section.

see attach!

![skills](https://cloud.githubusercontent.com/assets/18361424/14405527/8e8fd73a-fe99-11e5-8baa-c43646721def.png)

**Comment by callmekatootie** [comment]
Appears fine for me:

![image](https://cloud.githubusercontent.com/assets/2317133/14482850/ba0b573c-015e-11e6-9a7a-7b9b509f710e.png)
