### ISSUE TITLE
Android - end of results text even not loaded

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#168]
Android 6.0
HTC One M9
Chrome

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Go to main menu.

3) Complete search field with text "Greedy" and press enter.

actual: observe at the bottom of page the text "End of results".

expected: display "End of results" text only after some data was loaded(Load More button was available before).

![end-of-results_001](https://cloud.githubusercontent.com/assets/18361424/14405655/4a113966-fe9c-11e5-91bd-6e5f6d3103cb.png)

**Comment by callmekatootie** [comment]
Not a issue
