### ISSUE TITLE
Desktop - end of results text even not loaded

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#169]
Environment

Mozilla Firefox 45.0.1
Chrome 49.0.2623.112
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Complete search field with text "Greedy".

4) Press enter to perform search action.

actual: observe at the bottom of page the text "End of results" even was not loaded.

expected: do not display the text when no results was loaded before.

see attach!

![end-of-results_002](https://cloud.githubusercontent.com/assets/18361424/14405708/fb0a4c8a-fe9c-11e5-94fa-6131410ca8d7.png)

**Comment by callmekatootie** [comment]
Invalid issue

**Comment by onetliviunicu** [comment]
hy, as you can see there is a text End of results.This text appear in application only when multiple data are loaded, in this case when no other data was loaded the text must not be displayed.Can you please review again?

**Comment by callmekatootie** [comment]
I am not sure I understand.

I can see the data loaded above it - Hence the "End Of Results" below it. There is no more to load. What is the issue here? Can you create a video or share more snapshots with explanations

**Comment by onetliviunicu** [comment]
For this issue I think is not necessary to have "End of results" text there because only one record data is available.We suppose multiple data available and Lode More button which is pressed is very correct to have "End of results" but in this case not.Can you please verify again?

**Comment by nlitwin** [comment]
It's working as designed. There was another issue logged that suggested "End of results" should always show, which I believe @fnisen mentioned we'd take as a bug. In that case this was be a duplicate issue

**Comment by fnisen** [comment]
@onetliviunicu, @nlitwin - yes, confirming. We won't have any special logic for "End of results." It should always appear as long as there are any results.

**Comment by onetliviunicu** [comment]
This issue for "End of results" maybe is duplicate for an issue logged by me but not for others competitors.Please set a comment with duplicated issues.Thank you!
