### ISSUE TITLE
Most relevant search item is not listed on top

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#172]
Description
-----------------------------------------------------------------
Most relevant search item is not listed on top

Steps
-----------------------------------------------------------------
- Open the Topcoder Search Web Page

- https://www.topcoder-qa.com/search/members/?q=wend

- Check the search result

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- Must display the relevent results first
- Starts with "wend" must e display first

Actual result
-----------------------------------------------------------------
- Most relevant search item is not listed on top

Environment
-----------------------------------------------------------------
Chrome 49.0.2623.112 m, 
FF 45.0.1
iPhone 6s, Safari
iPhone 5, Safari
Samsung Galaxy S5, Android 5.0

Image/Video/JS Log
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![30](https://cloud.githubusercontent.com/assets/4592712/14407353/39c710c0-fee3-11e5-9251-2541b854a1d8.png)

**Comment by callmekatootie** [comment]
@fnisen @nlitwin Not sure the logic of ranking the usernames but I would assume that a user with lots of skillsets and activity is placed first?

**Comment by nlitwin** [comment]
Hmm, I believe we are not sorting them based on skills / activity and only by how elastic search matches the search term to the username. @fnisen Is this working as expected?

**Comment by fnisen** [comment]
Yes, the logic for usernames is strictly "best match." This critique seems valid to me.
