### ISSUE TITLE
[Common] Irrelevant skill sets displayed from some users

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#173]
Description
-----------------------------------------------------------------
[Common] Irrelevant skill sets displayed from some users

Steps
-----------------------------------------------------------------
- Open the Topcoder Search Web Page

- https://www.topcoder-qa.com/search/members/?q=dojo

- Check the record 8, dileepa (https://www.topcoder-qa.com/members/dileepa/)

- He won't participated to 'Cd' competiotions at all, but displayed in search results

- This is a common for some records

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- Must display the relevent skill sets only

Actual result
-----------------------------------------------------------------
- Irrelevant skill sets displayed from some users

Environment
-----------------------------------------------------------------
Chrome 49.0.2623.112 m, 
FF 45.0.1
iPhone 6s, Safari
iPhone 5, Safari
Samsung Galaxy S5, Android 5.0

Image/Video/JS Log
-----------------------------------------------------------------
![31](https://cloud.githubusercontent.com/assets/4592712/14407432/67e3879c-fee6-11e5-854c-09d9e93cfd8c.png)

**Comment by callmekatootie** [comment]
Duplicate issue. Have come across this before
