### ISSUE TITLE
[Common] No need to highlight the Skills in the 'Usernames matching XXX' section

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#174]
Description
-----------------------------------------------------------------
[Common] No need to highlight the Skills in the 'Usernames matching XXX' section

Steps
-----------------------------------------------------------------
- Open the Topcoder Search Web Page

- https://www.topcoder-qa.com/search/members/?q=j2ee

- Scroll down to the "Usernames matching j2ee"

- Check the Skills; They are highlighted and some of them are no relevent to 'J2EE'

- Because this section will match the username no need to highlight the skills

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- No need to highlight the Skills in the 'Usernames matching XXX' section
- Because this section will match the username no need to highlight the skills

Actual result
-----------------------------------------------------------------
- In 'Usernames matching XXX' section; It highlights the Skills 

Environment
-----------------------------------------------------------------
Chrome 49.0.2623.112 m, 
FF 45.0.1
iPhone 6s, Safari
iPhone 5, Safari
Samsung Galaxy S5, Android 5.0

Image/Video/JS Log
-----------------------------------------------------------------
![32](https://cloud.githubusercontent.com/assets/4592712/14407463/5c1a1af6-fee7-11e5-9027-fe1085555e15.png)

**Comment by callmekatootie** [comment]
@fnisen @nlitwin When the result is based on the username, is highlighting the skill set a bug?

**Comment by nlitwin** [comment]
Hmm good question, @fnisen? :)

**Comment by fnisen** [comment]
Yes, this is a bug.
