### ISSUE TITLE
'Find Users' must "Find Members" to be consistent with other locations

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#175]
Description
-----------------------------------------------------------------
'Find Users' must "Find Members" to be consistent with other locations

Steps
-----------------------------------------------------------------
- Open the Topcoder Search Web Page

- Click on the Search (Default text is : Find Members) and enter 'mysql'

- https://www.topcoder-qa.com/search/members/?q=mysql

- While searching check the text: Loading users...

- Check the search result: 'Member since Mar 2008'

- Check the Table heading "Top Members in MySql"

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- 'Find Users' must "Find Members" to be consistent with other locations

Actual result
-----------------------------------------------------------------
'Find Users' 

Environment
-----------------------------------------------------------------
Chrome 49.0.2623.112 m, 
FF 45.0.1
iPhone 6s, Safari
iPhone 5, Safari
Samsung Galaxy S5, Android 5.0

Image/Video/JS Log
-----------------------------------------------------------------
![33](https://cloud.githubusercontent.com/assets/4592712/14407491/a3943122-fee8-11e5-9dac-49c306df6be6.png)

**Comment by callmekatootie** [comment]
@fnisen @nlitwin I think the user here is telling that instead of Loading users it should be members (or the text Top Members should be Top users - for consistency). Bug?

**Comment by nlitwin** [comment]
I'll default to @fnisen on this one.

**Comment by fnisen** [comment]
Yes, fair, it's a bug.
