### ISSUE TITLE
Search icon in the Mobile view must align properly (Align Vertically)

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#176]
Description
-----------------------------------------------------------------
Search icon in the Mobile view must align properly (Align Vertically)

Steps
-----------------------------------------------------------------
- Open the Topcoder Search Web Page

- Click on the Search

- Check the search icon

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- Must align vertically

Actual result
-----------------------------------------------------------------
Search icon in the Mobile view must align properly 

Environment
-----------------------------------------------------------------
iPhone 6s, Safari
iPhone 5, Safari
Samsung Galaxy S5, Android 5.0

Image/Video/JS Log
-----------------------------------------------------------------
![7](https://cloud.githubusercontent.com/assets/4592712/14407537/cf26f2fa-feea-11e5-9aa2-94e03d205af0.PNG)

**Comment by callmekatootie** [comment]
I think the issue here is that it needs to be vertically centered.
