### ISSUE TITLE
the focus of the search text field should be set by default

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#177]
Mac 10.11.4 + FF45.0.1

1. open https://www.topcoder-qa.com/search/members/?q=javascript
2. hover on the search button
3. observe

expected: the focus of the search text field should be set by default, so that the user can enter the search text immediately. See Google search for reference.

actual: see screenshot, user has to click in the field in order to input the text.

![qq20160410-0 2x](https://cloud.githubusercontent.com/assets/4590317/14408685/81483e6c-ff31-11e5-9587-a0d7189e1c24.png)

**Comment by callmekatootie** [comment]
Not necessarily - the user might have hovered accidentally too
