### ISSUE TITLE
Red line validation on search text is displayed even the text is correct

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#178]
Environment

Chrome 49.0.2623.112
Windows 7

Description

1) Access application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Enter the text "hi4" and add a space.

Observe a red line validation under entered text.

4) Press back to delete the space added before.

Observe the red line is displayed even the text is correct.

actual: red validation line is displayed on entered text even the text is correct set.
expected: display the red line validation text only for text which are not allowed.

see attach!

[search.zip](https://github.com/appirio-tech/topcoder-app-r/files/211756/search.zip)

Noes

- please unzip to see the video file!

**Comment by callmekatootie** [comment]
That is a browser feature not app - I think it's checking your spelling
