### ISSUE TITLE
Auto suggest feature is not working

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#179]
Environment

Mozilla Firefox 45.0.1
Chrome 49.0.2623.112
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Search an existing user as example hi4sandy.

4) Press again on search icon.

5) Enter the first characters from username as example hi4

actual: auto suggest feature is not working.

expected: display a list with all available users which begin with these characters.

**Comment by callmekatootie** [comment]
There is no auto suggest feature
