### ISSUE TITLE
Do not perform the search when a space is in textfield

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#180]
Environment

Mozilla Firefox 45.0.1
Chrome 49.0.2623.112
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Add a space or more into search field.

4) Press enter to perform the search operation.

actual: the search function is performed and the message is displayed "Oops! There was an error.".
expected: is not necessary to redirect to page with the message just do not perform the search operation.

**Comment by callmekatootie** [comment]
Duplicate issue
