### ISSUE TITLE
Invalid results are displayed

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#181]
Environment

Mozilla Firefox 45.0.1
Chrome 49.0.2623.112
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Complete search field with text "C++++++++++++++++++++++++".

4) Press enter to perform the search operation.

actual: the results are displayed and the url is different.

expected: do not perform search for this text.

see attachments!

![mozilla_c](https://cloud.githubusercontent.com/assets/18361424/14410173/e13ebd88-ff30-11e5-851e-486aa878a7d1.png)
![c](https://cloud.githubusercontent.com/assets/18361424/14410174/e788f550-ff30-11e5-8b8e-ae72d1f88e0a.png)

**Comment by callmekatootie** [comment]
Duplicate issue
