### ISSUE TITLE
search results are not correct

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#182]
Mac 10.11.4 + FF45.0.1

1. open https://www.topcoder-qa.com/search/members/?q=hello-c
2. observe

expected: results should not contain “Top Members in C” data.

actual: see screenshot

![qq20160410-1 2x](https://cloud.githubusercontent.com/assets/4590317/14410841/520d4e64-ff6b-11e5-829a-af0eeaedbb04.png)

**Comment by callmekatootie** [comment]
@fnisen @nlitwin If there is a perfect match of the username, doesn't it show that first? There is a user named hello-c - at the bottom though. I mean, it doesn't show the top members in such a case right?

**Comment by nlitwin** [comment]
I think this is because of special characters not working, and so it might be a duplicate. The "-" isn't properly handled, and it thinks its the skill "C". The leaderboard shouldn't show up given the search term "hello-c".
