### ISSUE TITLE
reason for the error should be specified

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#183]
Mac 10.11.4 + FF45.0.1

1. open https://www.topcoder-qa.com/search/members/?q=&nbsp;hi&nbsp;
2. observe

expected: reason for the error should be specified

actual: see screenshot, not sure why the error occurred.
![qq20160410-2 2x](https://cloud.githubusercontent.com/assets/4590317/14410868/2b7eb55c-ff6c-11e5-8c84-192c1bc3d934.png)

**Comment by callmekatootie** [comment]
No. Technical errors are not shared with end users. I think the error message shown is fine
