### ISSUE TITLE
Improvment: the search section is not kept when chaange focus

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#184]
Environment

Mozilla Firefox 45.0.1
Chrome 49.0.2623.112
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Press on the search icon glass from the top right of page.

3) Move mouse over the blank section.

 Observe as the search section is hide.

actual: the search section is hide very easy.

expected: keep the search section visible.

see attach!

Notes

- treat this as an improvement and the reason because is logged is because the section is hide very easy.

**Comment by callmekatootie** [comment]
Can't take this as a bug but will share the feedback with them

@fnisen @nlitwin

**Comment by nlitwin** [comment]
This will be addressed with our new navigation coming out soon :)
