### ISSUE TITLE
Display the search field only when press enter on the search icon glass

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#185]
Environment

Mozilla Firefox 45.0.1
Chrome 49.0.2623.112
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Mouse over search icon glass from the top right of page.

actual: the search section is displayed.

expected: display the search section only when press enter on the search icon glass.

see attach!

section.swf

Notes

- treat this as an improvement I think is necessary because the user can very easy to move the mouse over the icon and the search section is displayed!

- please unzip the file to see the video!
[section.zip](https://github.com/appirio-tech/topcoder-app-r/files/211929/section.zip)

**Comment by callmekatootie** [comment]
How can the user press enter on an icon?

**Comment by onetliviunicu** [comment]
Which I wanted with this issue is as the search section to not be displayed when mouse over and only when the user click(right click mouse) button on search icon glass!
Can you please verify again?

**Comment by nlitwin** [comment]
This is working as intended. The UX will be updated when we come out with our new navigation in the near future.

**Comment by onetliviunicu** [comment]
ok, thank you!
