### ISSUE TITLE
Top members in C instead Top members in C#

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#186]
Environment

Mozilla Firefox 45.0.1
Chrome 49.0.2623.112
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript

2) Mouse over search icon glass from the top right of page.

3) Set C# and press enter.

expected: in result page the text is "Top Members in C" and must be "Top Members in C#".

![1](https://cloud.githubusercontent.com/assets/18361424/14412417/01bbf7da-ff6b-11e5-99b9-7e55921653d7.png)

**Comment by callmekatootie** [comment]
Duplicate bug
