### ISSUE TITLE
Write correct the search string

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#188]
Environment

Mozilla Firefox 45.0.1
Chrome 49.0.2623.112
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Mouse over search icon glass.

3) Complete search field with text "ABC".

actual: the text "Usernames matching abc"  is displayed.

expected: write the correct text "Usernames matching ABC" as was entered by user.

see attach!

![abc](https://cloud.githubusercontent.com/assets/18361424/14412771/ba9cfbb2-ff72-11e5-9673-47e975827394.png)
abc.png

**Comment by callmekatootie** [comment]
Can't reproduce:

![image](https://cloud.githubusercontent.com/assets/2317133/14483186/ea92674e-0161-11e6-9a6e-29bf7000df93.png)

**Comment by nlitwin** [comment]
This is actually a bug that I've had on my to do list and I just pushed up new code today that changes that behavior. We can give credit for this, as it was a bug at the time.
