### ISSUE TITLE
cannot search for “so”

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#19]
Mac 10.11.4 + FF45.0.1

1. open https://www.topcoder-qa.com/search/members/?q=so
2. observe

expected: there should be users listed, e.g. “soso0574” is a valid output

actual: see screenshot

![qq20160409-43 2x](https://cloud.githubusercontent.com/assets/4590317/14402581/cde7be84-fe6c-11e5-9713-5b5d0241ea8d.png)

**Comment by nlitwin** [comment]
Asana task created and assigned
