### ISSUE TITLE
Invalid results for search criteria set in field

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#190]
Environment

Mozilla Firefox 45.0.1
Chrome 49.0.2623.112
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Mouse over search icon glass.

3) Complete search field with {{{.

4) Press enter.

actual: Oops! There was an error.

expected: do not treat these characters 

expected: do not treat this character as invalid.

**Comment by callmekatootie** [comment]
Duplicate - special characters should be handled properly

**Comment by onetliviunicu** [comment]
Can you please set a comment with duplicated issue?

**Comment by callmekatootie** [comment]
Duplicate of https://github.com/appirio-tech/topcoder-app-r/issues/53
