### ISSUE TITLE
Result for search criteria set in field are invalid

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#192]
Environment

Mozilla Firefox 45.0.1
Chrome 49.0.2623.112
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Mouse over search icon glass.

3) Complete search field with |||.

4) Press enter to perform the search.

actual: Oops! There was an error.

expected: do not display the error page because this can be a valid username.

**Comment by callmekatootie** [comment]
Duplicate - handle user a|a
