### ISSUE TITLE
Error determining if search term is a tag: TypeError: l["default"](...) is undefined

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#193]
Environment

Mozilla Firefox 45.0.1
Chrome 49.0.2623.112
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Mouse over search icon glass.

3) Complete search field with "+++".

4) Press enter.

actual: the firebug error message is displayed Error determining if search term is a tag: TypeError: l["default"](...) is undefined.

expected: do not return this error message in console.

see attach!

![error_001](https://cloud.githubusercontent.com/assets/18361424/14412926/fefcf724-ff74-11e5-938c-707fe3891487.png)

**Comment by callmekatootie** [comment]
Duplicate - Special characters should be handled properly

**Comment by onetliviunicu** [comment]
Can you please set a comment with duplicated issue?
Thank you!

**Comment by callmekatootie** [comment]
Duplicate of https://github.com/appirio-tech/topcoder-app-r/issues/53
