### ISSUE TITLE
Invalid result when search %%%

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#194]
Environment

Mozilla Firefox 45.0.1
Chrome 49.0.2623.112
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Mouse over search icon glass.

3) Complete search field with "%%%".

4) Press enter for search.

actual: userundefined is returned.

expected: do not display this user.

see attach!

![userundefined](https://cloud.githubusercontent.com/assets/18361424/14412955/71e08148-ff75-11e5-8ac1-12b5a6f2fc04.png)

**Comment by onetliviunicu** [comment]
After search operation the link is changed into "https://www.topcoder-qa.com/search/members/?q=undefined"

**Comment by callmekatootie** [comment]
Duplicate - Special characters should be handled properly

**Comment by onetliviunicu** [comment]
Can you please set a comment with duplicated issue?
Thank you!

**Comment by callmekatootie** [comment]
Duplicate of https://github.com/appirio-tech/topcoder-app-r/issues/53
