### ISSUE TITLE
Android: invalid search result for %%%

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#195]
Android 6.0
HTC One M9
Chrome

Access application link https://www.topcoder-qa.com/search/members.

Go to menu.

Complete search field with "%%%".

Press enter.

actual: undefineduser is returned.

expected: do not display this user.

![undefined](https://cloud.githubusercontent.com/assets/18361424/14412999/6bfc8fdc-ff76-11e5-8fa0-21cf374e2097.png)

**Comment by callmekatootie** [comment]
Duplicate - Special characters should be handled properly

**Comment by onetliviunicu** [comment]
This issue can be duplicate of https://github.com/appirio-tech/topcoder-app-r/issues/53?
The issue here is as the results as you can see in attachment "userundefined" is received for searching of "%%%".Yes can be special chars but why only in this case the "userundefined" is received and for other cases this is not?

**Comment by callmekatootie** [comment]
You can't investigate why a bug is caused by another bug :) You only deal with the source not with its effect.
