### ISSUE TITLE
NetworkError: 401 Unauthorized when use load more button

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#196]
Environment

Firebug
Mozilla Firefox 45.0.1
Chrome 49.0.2623.112
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Mouse over search icon glass.

3) Complete search field with text "aaa".

4) Press enter.

5) Open Firebug tool.

actual: the error is displayed ""NetworkError: 401 Unauthorized - http://res.cloudinary.com/hnep56ea0/image/upload/c_fill,h_125,w_125/daaain.jpg"".

expected: do not display this error in console.

see attach!

![cloud](https://cloud.githubusercontent.com/assets/18361424/14413020/e90c8d2e-ff76-11e5-8115-9333d6c0a31c.png)

**Comment by callmekatootie** [comment]
@fnisen @nlitwin Bug? I do see this too - its for the user daaain

**Comment by nlitwin** [comment]
Hmm, seems like an invalid photoURL. We can accept this as a bug, since it's not the known gravatar url bug.
