### ISSUE TITLE
No results found for sk

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#197]
Environment

Firebug
Mozilla Firefox 45.0.1
Chrome 49.0.2623.112
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Mouse over search icon glass.

3) Complete search field with text "sk".

4) Press enter.

actual: no results found and redirect to page with text "Sorry, no results found for sk" even an existing username exist "Sky_".

expected: display correct results on page.

**Comment by callmekatootie** [comment]
Duplicate - less than 3 character search not working as expected

**Comment by onetliviunicu** [comment]
This issue is set as Duplicate - less than 3 character search not working as expected.Can you please set a comment with number of duplicated issue?
Thank you!

**Comment by callmekatootie** [comment]
Duplicate of https://github.com/appirio-tech/topcoder-app-r/issues/19
