### ISSUE TITLE
The error is displayed when search an existing name

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#199]
Environment

Firebug
Mozilla Firefox 45.0.1
Chrome 49.0.2623.112
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Mouse over search icon glass.

3) Complete search field with text "sky q=test".

4) Press enter.

actual: redirect to error page with the message "Oops! There was an error.".

expected: do not treat this string as invalid.

**Comment by callmekatootie** [comment]
Duplicate - Special characters should be handled properly (the = here)
