### ISSUE TITLE
Invalid result when search q=9

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#200]
Environment

Firebug
Mozilla Firefox 45.0.1
Chrome 49.0.2623.112
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Mouse over search icon glass.

3) Complete search field with "q=9".

4) Press enter.

actual: redirect to invalid search result page with text Oops! There was an error.

expected: do not display this.

Notes

- w=9 works correct!

**Comment by onetliviunicu** [comment]
Notes

- the reason for this issue can be because the URL contain q=

**Comment by callmekatootie** [comment]
Duplicate - Special characters should be handled properly
