### ISSUE TITLE
Blank page for string searched

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#201]
Environment

Firebug
Mozilla Firefox 45.0.1
Chrome 49.0.2623.112
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Mouse over search icon glass.

3) Complete search field with text 'test&q=ana'.

4) Press enter.

actual blank page is returned.

expected: display correct results.

see attach!

![error1](https://cloud.githubusercontent.com/assets/18361424/14413185/cb06ff90-ff7a-11e5-8e09-a38a2faebac4.png)

**Comment by callmekatootie** [comment]
Duplicate - Special characters should be handled properly

**Comment by onetliviunicu** [comment]
Can you please set the duplicate number issue?

**Comment by callmekatootie** [comment]
Duplicate of https://github.com/appirio-tech/topcoder-app-r/issues/53
