### ISSUE TITLE
Image for invalid page must be changed

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#202]
Environment

Firebug
Mozilla Firefox 45.0.1
Chrome 49.0.2623.112
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Mouse over search icon glass.

3) Complete the search field with '.'.

4) Press enter.

actual: redirect to the page with text "Sorry, no results found for .".

expected: change the image with the image from attach!

![ffc96c4e-ff7b-11e5-91c8-8730c554cbd7](https://cloud.githubusercontent.com/assets/18361424/14413242/9bf99f58-ff7c-11e5-815f-5732085c88a7.png)

**Comment by callmekatootie** [comment]
Can't make out why they should use that image and not this one:

![image](https://cloud.githubusercontent.com/assets/2317133/14483306/50d2bd32-0163-11e6-8ea1-5d3e8bba6a01.png)
