### ISSUE TITLE
The error message and invalid must be differentiated

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#203]
Environment

Firebug
Mozilla Firefox 45.0.1
Chrome 49.0.2623.112
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Mouse over search icon glass.

3) Complete search field with ".".

4) Observe the page https://www.topcoder-qa.com/search/members/?q=. for no results.

**Comment by callmekatootie** [comment]
@fnisen @nlitwin Basically, the user wants you to display a different type of page for no results vs when an error has occurred. Valid?

**Comment by nlitwin** [comment]
Hmm, do they mean a different icon? We do have a no results page and an error page, they just look very similar.

**Comment by callmekatootie** [comment]
@nlitwin Maybe a different icon but something to distinguish that its an error vs no results. Valid bug?

**Comment by nlitwin** [comment]
Well the "No Results" page shows "Sorry, no results found for X", and the error page shows "Oops! There was an error."

**Comment by callmekatootie** [comment]
I get that... I'll not take this as a bug.

**Comment by nlitwin** [comment]
I dunno, @fnisen do you think there should be a bigger difference between the two?

**Comment by fnisen** [comment]
@nlitwin ideally, but I think we're addressing basic expectations.
