### ISSUE TITLE
[Common] Irrelevant Users displayed; when there are no users with wins inside the top 10

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#204]
Description
-----------------------------------------------------------------
[Common] Irrelevant Users displayed; when there are no users with wins inside the top 10

Steps
-----------------------------------------------------------------
- Open the Topcoder Search Web Page

- Click on the Search and type 'illustrator' and search

- https://www.topcoder-qa.com/search/members/?q=illustrator

- Check the record 9-10

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- Must display the correct user set

Actual result
-----------------------------------------------------------------
Irrelevant Users displayed; when there are no users with wins inside the top 10

Environment
-----------------------------------------------------------------
Chrome 49.0.2623.112 m, 
FF 45.0.1
iPhone 6s, Safari
iPhone 5, Safari
Samsung Galaxy S5, Android 5.0

Image/Video/JS Log
-----------------------------------------------------------------
![35](https://cloud.githubusercontent.com/assets/4592712/14416013/1858eb26-ffc3-11e5-93ad-72da62cd0671.png)

**Comment by callmekatootie** [comment]
Duplicate - there are many tickets with irrelevant results returned already
