### ISSUE TITLE
[Common] When user search 'design'; it will populate the 'Mobile Design'

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#207]
Description
-----------------------------------------------------------------
[Common] When user search 'design'; it will populate the 'Mobile Design'

Steps
-----------------------------------------------------------------
- Open the Topcoder Search Web Page

- Click on the Search and type 'design' and search

- https://www.topcoder-qa.com/search/members/?q=design

- Check the Title; it is displaying as 'Mobile Design'

- https://www.topcoder-qa.com/search/members/?q=designs

- It will display matching users

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- 'Must display the correct matching users or skills

Actual result
-----------------------------------------------------------------
When user search 'design'; it will populate the 'Mobile Design'

Environment
-----------------------------------------------------------------
Chrome 49.0.2623.112 m, 
FF 45.0.1
iPhone 6s, Safari
iPhone 5, Safari
Samsung Galaxy S5, Android 5.0

Image/Video/JS Log
-----------------------------------------------------------------
![38](https://cloud.githubusercontent.com/assets/4592712/14417777/7313ab56-ffd6-11e5-92de-92e9dfa69466.png)

**Comment by callmekatootie** [comment]
Duplicate - search results dont match the query
