### ISSUE TITLE
[Common] Irrelevant Users displayed when we search the skill set "Twitter"

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#208]
Description
-----------------------------------------------------------------
[Common] Irrelevant Users displayed when we search the skill set "Twitter"

Steps
-----------------------------------------------------------------
- Open the Topcoder Search Web Page

- Click on the Search and type 'twitter' and search

- hhttps://www.topcoder-qa.com/search/members/?q=twitter

- Check the Search list; some of them won't listed 'twitter' as their skills

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- 'Must display the members with 'twitter' skills

Actual result
-----------------------------------------------------------------
 Irrelevant Users displayed when we search the skill set "Twitter"

Environment
-----------------------------------------------------------------
Chrome 49.0.2623.112 m, 
FF 45.0.1
iPhone 6s, Safari
iPhone 5, Safari
Samsung Galaxy S5, Android 5.0

Image/Video/JS Log
-----------------------------------------------------------------
![39](https://cloud.githubusercontent.com/assets/4592712/14417806/d270cda4-ffd6-11e5-9d11-4f2d682951b7.png)

**Comment by callmekatootie** [comment]
Duplicate - search results dont match the query string
