### ISSUE TITLE
[Common] "Twitter" skill set have two forms when searching

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#209]
Description
-----------------------------------------------------------------
[Common] "Twitter" skill set have two forms when searching

Steps
-----------------------------------------------------------------
- Open the Topcoder Search Web Page

- Click on the Search and type 'twitter' and search

- hhttps://www.topcoder-qa.com/search/members/?q=twitter

- Check the Search list; You can see 'Bootstrap' also

- When we are searching user didn't input 'Bootstrap' as a keyword. If the 'Bootstrap' and 'Twitter Bootstrap' are recognized as same; List must consist both form. CHeck the below example.

- Search the below options as well; https://www.topcoder-qa.com/search/members/?q=bootstrap  AND  https://www.topcoder-qa.com/search/members/?q=twitter%20bootstrap

- Check the Search list; 

- twitter bootstrap = twitter AND Bootstrap = Bootstrap

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- 'Must display only one single skill set. or Both 'Bootstrap' and 'Twitter Bootstrap' must be recognized as one.

Actual result
-----------------------------------------------------------------
"Twitter" skill set have two forms when searching

Environment
-----------------------------------------------------------------
Chrome 49.0.2623.112 m, 
FF 45.0.1
iPhone 6s, Safari
iPhone 5, Safari
Samsung Galaxy S5, Android 5.0

Image/Video/JS Log
-----------------------------------------------------------------
![40 1](https://cloud.githubusercontent.com/assets/4592712/14417929/14be67d8-ffd8-11e5-8051-01e5df678434.png)
![40 2](https://cloud.githubusercontent.com/assets/4592712/14417930/14eca382-ffd8-11e5-83e0-5c84bf5dbee6.png)

**Comment by callmekatootie** [comment]
Duplicate - the search results don't match the searched string
