### ISSUE TITLE
error occurred if we search for empty string

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#22]
Mac 10.11.4 + FF45.0.1

1. open https://www.topcoder-qa.com/search/members/?q=
2. observe

expected: should handle empty string properly

actual: see screenshot
![qq20160409-44 2x](https://cloud.githubusercontent.com/assets/4590317/14402586/1304da9c-fe6d-11e5-8b65-7f6df70c00ae.png)

**Comment by vikasrohit** [comment]
[Asana Task](https://app.asana.com/0/95614844085038/113534202832111)

**Comment by nlitwin** [comment]
Closing since we are tracking in Asana
