### ISSUE TITLE
Loading page without query produces errors in console

### ISSUE THREAD

**Issue by Colinh84** [appirio-tech/topcoder-app-r#24]
Description:
Loading page https://www.topcoder-dev.com/search/members/ without query results in a blank page and the error: TypeError: Cannot read property 'toLowerCase' of undefined in console.

Steps to Reproduce:
- Load https://www.topcoder-dev.com/search/members/
- Look in console, notice error.

Expected: Blank search results page.
Actual: blank page with errors.

Screenshot: http://i.imgur.com/xtfpW4F.png
**Requirements**
- [ ] Please adhere to the code style specified in the readme.
- [ ] Make sure the component is rendered correctly on all screen sizes as specified in the designs

**Resources**
 -

**Comment by callmekatootie** [comment]
Reproducible in QA too.
