### ISSUE TITLE
string is not trimmed while searching

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#25]
Mac 10.11.4 + FF45.0.1

1. open https://www.topcoder-qa.com/search/members/?q=   winter      (note that there are some spaces before and after "winter")
2. observe

expected: should trim the string before searching

actual: see screenshot

![qq20160409-45 2x](https://cloud.githubusercontent.com/assets/4590317/14402592/4831fc22-fe6d-11e5-8e1b-e60723297369.png)

**Comment by callmekatootie** [comment]
@fnisen Is this a bug? The input field does trim but changing the URL does not do that. I assume the trim function is on the client and not server.

1. The backend can trim and fetch the relevant results but then one could argue that they searched for space_winter and not just winter. Not sure if this mismatch between the searched query and URL query param is valid - moreover, the server could redirect the user to the trimmed query param

**Comment by fnisen** [comment]
Hmm... I think this is pushing what would be likely user behavior, but consistency between the two entry methods is a best practice, so Iet's allow.

**Comment by nlitwin** [comment]
@vikasrohit Can we make sure that the new search bar trims the values entered in the input field?

**Comment by vikasrohit** [comment]
Definitely. 👍 [Asana Task](https://app.asana.com/0/95614844085038/113534192025964)

**Comment by nlitwin** [comment]
Thanks! :)

**Comment by fnisen** [comment]
@vikasrohit I can't access that Asana task. Maybe it's private? Thanks.

**Comment by nlitwin** [comment]
Closing since we are tracking in Asana

**Comment by vikasrohit** [comment]
Made the task public
