### ISSUE TITLE
Edit button should not be shown if no Recent Search items

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#27]
Mac 10.11.4 + FF45.0.1

1. open https://www.topcoder-qa.com/search/members/?q=javascript
2. click the search box, click “Edit” , observe

expected: should not show Edit button if it’s not clickable

actual: see screenshot
![qq20160409-19 2x](https://cloud.githubusercontent.com/assets/4590317/14402160/3b6527d0-fe5e-11e5-806c-c248d0e2ef2f.png)

**Comment by callmekatootie** [comment]
Not a QA Issue.
