### ISSUE TITLE
Loading page with query in URL is not reflected in search bar

### ISSUE THREAD

**Issue by Colinh84** [appirio-tech/topcoder-app-r#28]
Loading a page with the query in URL does not fill the query into the search bar, leaving it empty.

Steps to Reproduce:
- Load a URL such as: https://www.topcoder-dev.com/search/members/?q=test
- Notice that after page loads, search bar is empty

Expected:
- Query should fill into search bar

Actual:
- Search bar empty

Screenshot: http://i.imgur.com/e0fwQoF.png
**Requirements**
- [ ] Please adhere to the code style specified in the readme.
- [ ] Make sure the component is rendered correctly on all screen sizes as specified in the designs

**Resources**
 -

**Comment by callmekatootie** [comment]
Issue in QA too.

Will take this as a bug since Youtube / Google don't erase the search content when results are loaded. If this is a bug or feature, only topcoder devs can tell but I understand why the user has marked this as bug based on the popular behaviour

**Comment by nlitwin** [comment]
I'm not sure we planned this as a feature and is a bug. @fnisen? What do you think? I was under the impression that we weren't making updates to the current header/search bar.

**Comment by fnisen** [comment]
@callmekatootie, @nlitwin - let's keep it as a bug. 
Yes, we hadn't planned on handling this case because we're not updating the search bar (a new one is coming), but this is reasonable behavior to expect.

**Comment by nlitwin** [comment]
@fnisen Is this something we want in the new search bar? fyi @vikasrohit

**Comment by fnisen** [comment]
@nlitwin, @vikasrohit - ideally we would, but can you let me know the effort required before we decide?

**Comment by nlitwin** [comment]
Vikas would we just use `componentWillMount` of the `SearchBar` to look at the URL and see if there's a search term? If so, pass it down as a prop to be used as the value of the input?

**Comment by vikasrohit** [comment]
Yes, @nlitwin I think that would be it. :)

**Comment by fnisen** [comment]
@vikasrohit same issue--can't access the task

**Comment by nlitwin** [comment]
I wonder if it's a private task with no Project set?

**Comment by nlitwin** [comment]
Closing since we are tracking in Asana

**Comment by vikasrohit** [comment]
Made the task public.
