### ISSUE TITLE
no need to show badge if the user has no avatar 

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#29]
Mac 10.11.4 + FF45.0.1

1. open https://www.topcoder-qa.com/search/members/?q=javascript
2. observe users list

expected: no need to show badge if the user has no avatar 

actual: see screenshot

![qq20160409-46 2x](https://cloud.githubusercontent.com/assets/4590317/14402604/82dcba4c-fe6d-11e5-8222-e4460d260d4d.png)

**Comment by callmekatootie** [comment]
Why not? The badge is for the reputation, not for the profile pic
