### ISSUE TITLE
[Common] When Searching users; it will display the list page and them display the error page

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#30]
Description
-----------------------------------------------------------------
[Common] When Searching users; it will display the list page and them display the error page

Steps
-----------------------------------------------------------------
- Open the Topcoder Search Web Page

- Click Search

- Enter 'testsdgun'

- You can see the table displayed for moment and them display user not found message

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- Must not display the searching animation; If there is no users such as.
- Must directly display the validation message

Actual result
-----------------------------------------------------------------
When Searching users; it will display the list page and them display the error page

Environment
-----------------------------------------------------------------
Chrome 49.0.2623.112 m, 
FF 45.0.1, 

Image/Video/JS Log
-----------------------------------------------------------------

**Comment by sdgun** [comment]
http://www.screencast.com/t/Y2FPKX5C

**Comment by callmekatootie** [comment]
@fnisen Do I take this as a bug. From a UX perspective, it behaves a lot like Facebook does with its post - where it indicates that a post will come (in case the net is slow) and then load the post. In this case, it just shows the list view and then realizes that there are no results.

**Comment by nlitwin** [comment]
This is working as expected. It should show the empty "loading" list and then no results if there are none.

**Comment by fnisen** [comment]
Yes, agree.
