### ISSUE TITLE
“End of results” should be “End of Results”

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#32]
Mac 10.11.4 + FF45.0.1

1. open https://www.topcoder-qa.com/search/members/?q=javascript
2. observe the top and bottom text

expected: “End of results” should be “End of Results” for consistency, since on the top there is "Top Members in Javascript", not "Top members in Javascript".

actual: see screenshots

![qq20160409-47 2x](https://cloud.githubusercontent.com/assets/4590317/14402616/b5130db8-fe6d-11e5-9a49-6a46e68a2ebe.png)
![qq20160409-48 2x](https://cloud.githubusercontent.com/assets/4590317/14402617/b78bd5e8-fe6d-11e5-955f-7ea90018bc09.png)

**Comment by callmekatootie** [comment]
Sorry, not a valid issue.
