### ISSUE TITLE
no “End of results” shown when searching c++

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#36]
Mac 10.11.4 + Chrome 49.0

1. open https://www.topcoder-qa.com/search/members/?q=c++
2. observe the bottom 

expected: should show “End of results” below the table.

actual: see screenshot

![qq20160409-50 2x](https://cloud.githubusercontent.com/assets/4590317/14402626/0596aca4-fe6e-11e5-91e5-a44feedcac3f.png)

**Comment by callmekatootie** [comment]
There's no pagination and if I search using `javascript` then I do get End of Results - Seems like it's only for Usernames and not for Top Members in that skillset
