### ISSUE TITLE
 cannot search skill “Geometry”

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#40]
Mac 10.11.4 + Chrome 49.0

1. open https://www.topcoder-qa.com/search/members/?q=geom
2. observe

expected: should show the users with skill “Geometry”

actual: see screenshot, only username with 'geom" is shown

![qq20160409-51 2x](https://cloud.githubusercontent.com/assets/4590317/14402632/448e28ec-fe6e-11e5-8511-58b1b73e1f12.png)

**Comment by callmekatootie** [comment]
@fnisen Partial search supported?

**Comment by nlitwin** [comment]
Partial search of skills is not supported. JavaScript/jAvAsCriPT/javascript should all return a leaderboard of members with the skill JavaScript, but something like `javasc` should not return a leaderboard.

**Comment by fnisen** [comment]
Agree. This would be better supported with typeahead. It's hard for us to do partial search when it could be a legitimate username.
