### ISSUE TITLE
all skills should have same color

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#41]
Mac 10.11.4 + Chrome 49.0

1. open https://www.topcoder-dev.com/search/members/?q=c++
2. observe users’ skills

expected: all skills should have same color

actual: see screenshot, first one is in black but others are all in gray

![qq20160409-52 2x](https://cloud.githubusercontent.com/assets/4590317/14402648/c0d71e40-fe6e-11e5-9672-4d47d063646c.png)

**Comment by callmekatootie** [comment]
Not a valid issue - the highlighted skill set clearly is the one that was used to consider for the search

**Comment by nlitwin** [comment]
The first skill should definitely be highlighted, but it should say `Top Members in C++` and the highlighted skill should be `C++`. This is a bug, but it's the same bug as the issue regarding searching for `Windows Phone`.
