### ISSUE TITLE
Recent Search edit button is not working 

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/topcoder-app-r#44]
after searching if click on edit button , button is not working 

Steps To reproduce:
1. launch the site
2. login with user sweta.ipec pwd: sweta@123
3. go to search
4. search
5. click on edit button 

Expected Result: button should work 

Actual Result: not working

**Comment by swetaipec** [comment]
![image](https://cloud.githubusercontent.com/assets/16131461/14402228/eff9f418-fe4b-11e5-9248-43a591456c44.png)

**Comment by callmekatootie** [comment]
Not a QA issue
