### ISSUE TITLE
Menu: Page not found

### ISSUE THREAD

**Issue by madhusaha26** [appirio-tech/topcoder-app-r#47]
Steps:
1. Click https://www.topcoder-dev.com/search/members/?q=javascript
2. Click on Menu -page not found

Actual:
Menu- Page not found

Expected:
Menu page should work
![img_4056 1](https://cloud.githubusercontent.com/assets/7139655/14402235/63ab4ff6-fe4c-11e5-89a2-3a02dc43f3d5.PNG)

 -

**Comment by callmekatootie** [comment]
You need to specify which browser!

Tested on iPad Air 2 - works fine for me
