### ISSUE TITLE
[Common] Can't search in Chrome

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#49]
Description
-----------------------------------------------------------------
[Common] Can't search in Chrome

Steps
-----------------------------------------------------------------
- Open the Topcoder Search Web Page

- Click Search

- Enter 'h'

- It will redirect the page

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- Must be able to search the members, challenages and content

Actual result
-----------------------------------------------------------------
Can't search in Chrome

Environment
-----------------------------------------------------------------
Chrome 49.0.2623.112 m, 

Image/Video/JS Log
-----------------------------------------------------------------

**Comment by callmekatootie** [comment]
Duplicate of #19 - Can't search with less than 3 characters
