### ISSUE TITLE
if click on filtered result after search , it should navigate to particular result 

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/topcoder-app-r#50]
I entered Transact-SQL in search box ,in suggestion its showing but if I click on suggestion its not navigating to particular result

Steps To Reproduce:
1. Launch the site
2. Login with sweta.ipec pwd: sweta@124
3. go to search
4. Enter string as Transact-SQL
5. Click on Transact-SQL 

![image](https://cloud.githubusercontent.com/assets/16131461/14402245/efaef03e-fe4c-11e5-8369-01fec6e315b3.png)

**Comment by callmekatootie** [comment]
Not a QA issue
