### ISSUE TITLE
[common] tiny issue when hovering on the search box

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#51]
Mac 10.11.4 + Chrome 49.0
1. open https://www.topcoder-qa.com/search/members/?q=javascript
2. hover the cursor on the Search button, observe the text

expected: the text "FIND MEMBERS" should be moved a little right to the left line.

actual: see screenshot, they're too close

![qq20160409-56 2x](https://cloud.githubusercontent.com/assets/4590317/14402693/a179edce-fe6f-11e5-8cb2-b3727198cfe0.png)

**Comment by callmekatootie** [comment]
It is indeed way too close to the border
