### ISSUE TITLE
Recent search item is not visible 

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/topcoder-app-r#52]
Steps to reproduce:
1. launch the site 
2 . Login with sweta.ipec  pwd: sweta@123
3. go to search
4. go to recent search

Expected Result : recent search item should display
Actual Result:  not visible 

![image](https://cloud.githubusercontent.com/assets/16131461/14402258/89c648d4-fe4d-11e5-9678-f41c0442f4df.png)

**Comment by callmekatootie** [comment]
Not a QA issue
