### ISSUE TITLE
setState() console error when conducting second search

### ISSUE THREAD

**Issue by Colinh84** [appirio-tech/topcoder-app-r#54]
After an initial search in Chrome, searching for another term results in the error:

usersnap2-10976-en.js:4037 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.

and no new results return, leaving previous search query results on page.

Expected:
New query results returned.
Actual:
setState() error and old results remain on page.

Screenshot: http://i.imgur.com/Bamp39K.png
**Requirements**
- [ ] Please adhere to the code style specified in the readme.
- [ ] Make sure the component is rendered correctly on all screen sizes as specified in the designs

**Resources**
 -

**Comment by callmekatootie** [comment]
Not a QA issue
