### ISSUE TITLE
slash should be removed if no Country presented

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#55]
Mac 10.11.4 + Chrome 49.0

1. open https://www.topcoder-dev.com/search/members/?q=xml
2. observe “Ghostar”

expected: slash should be removed if no Country presented

actual: see screenshot

![qq20160409-58 2x](https://cloud.githubusercontent.com/assets/4590317/14402731/9b7104fc-fe70-11e5-855d-ad2fac34e2ea.png)

**Comment by callmekatootie** [comment]
He seems to have a country against him:

![image](https://cloud.githubusercontent.com/assets/2317133/14450856/bda98a5e-009f-11e6-92e1-53f60028f3fa.png)
