### ISSUE TITLE
search box should be shorter

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#56]
Mac 10.11.4 + Chrome 49.0

1. open https://www.topcoder-qa.com/search/members/?q=javascript
2. hover on the search button
3. observe

expected: no need to make the search box too long

actual: see screenshot

![qq20160409-28 2x](https://cloud.githubusercontent.com/assets/4590317/14402739/b9e46fc8-fe70-11e5-8374-4f2743c44fb6.png)

**Comment by callmekatootie** [comment]
Not a valid issue - that's how the element is designed
