### ISSUE TITLE
No need to show a label if the count is zero

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#57]
Mac 10.11.4 + Chrome 49.0

1. open https://www.topcoder-qa.com/search/members/?q=PSYHO
2. observe the labels

expected: no need to show a label if the count is 0

actual: see screenshot

![qq20160409-29 2x](https://cloud.githubusercontent.com/assets/4590317/14402742/cbf9b7c2-fe70-11e5-8569-9fcf2b7f7eff.png)

**Comment by callmekatootie** [comment]
@fnisen Valid bug?

**Comment by nlitwin** [comment]
This is working as expected. We've discussed hiding them if they are 0, but we're keeping it for now, unless the production data shows tons of 0s, in which case we might filter them out. @fnisen

**Comment by fnisen** [comment]
Yes, not a bug. It actually may be reflective of the member's performance.
