### ISSUE TITLE
tags should be all in uppercase

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#59]
Mac 10.11.4 + Chrome 49.0

1. open https://www.topcoder-qa.com/search/members/?q=xml
2. observe the labels

expected: tags should be all in uppercase

actual: see screenshot

![qq20160409-30 2x](https://cloud.githubusercontent.com/assets/4590317/14402309/39d22a2a-fe64-11e5-9d94-7ec841626e96.png)

**Comment by callmekatootie** [comment]
There does appear to be inconsistency in the capitalization of the tags. Will accept it

**Comment by nlitwin** [comment]
Those are not tags, but subtrack abbreviations. Ar = Architecture for example. There will be tooltips in the very near future that will help provide this information. This is working as expected.
