### ISSUE TITLE
The top line have different size

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#62]
Environment

Chrome 47.0.2526.73

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Press on the search icon glass from the top right of page.

-----------------------------------------------------------------------------------------------------------

actual: observe as border top and left / right lines are different for search field.

expected: set the same size for borders lines of fields.

-----------------------------------------------------------------------------------------------------------

see attach!

![different-size](https://cloud.githubusercontent.com/assets/18361424/14402321/d4d20e02-fe3a-11e5-9a55-1a09a7bfcaed.png)

**Comment by callmekatootie** [comment]
I'll accept it. You mean the border width and I feel that it should not show the outline on hover - just the bottom border is fine
