### ISSUE TITLE
[Common] Some skill sets for some users are not displayed

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#63]
Description
-----------------------------------------------------------------
[Common] Some skill sets for some users are not displayed

Steps
-----------------------------------------------------------------
- Open the Topcoder Search Web Page

- https://www.topcoder-qa.com/search/members/?q=sdgun

- Check the skill set; 'TEST SCENARIOS' is not displayed

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- Must display the all

Actual result
-----------------------------------------------------------------
Some skill sets for some users are not displayed

Environment
-----------------------------------------------------------------
Chrome 49.0.2623.112 m, 
FF 45.0.1, 
IE 11
iPhone 6s, Safari

Image/Video/JS Log
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![11](https://cloud.githubusercontent.com/assets/4592712/14402336/58e570d4-fe50-11e5-9517-fab25f0b351d.png)

**Comment by callmekatootie** [comment]
I'll accept it - it should not show the 0 ones if there is a track with more than 0 value

**Comment by nlitwin** [comment]
The subtracks are sorted by the `mostRecentEventDate` field and not by a member's score. We've discussed alternate ways of sorting the subtracks, but some subtracks have wins, others have rating, etc. so it's not easy to compare all subtracks. This is working as expected.
