### ISSUE TITLE
hovering on a skill should make the link to search that skill

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#65]
Mac 10.11.4 + Chrome 49.0

1. open https://www.topcoder-qa.com/search/members/?q=mig29
2. hover on the “Greedy” skill label, observe the link

expected: it should let the link to be “https://www.topcoder-qa.com/search/members/?q=Greedy” 

actual: it still links to user profile

![qq20160409-32 2x](https://cloud.githubusercontent.com/assets/4590317/14402340/6204153e-fe65-11e5-83a2-b3985cc472e6.png)

**Comment by callmekatootie** [comment]
@fnisen I will not take this as a bug but this could be a nice feature - let me know if you want me to accept this as abug

**Comment by fnisen** [comment]
@callmekatootie - yes, not a bug because there is no highlighting to indicate that the skill can be a search term. It is already a planned feature for the future. :)
