### ISSUE TITLE
When the text is set in field don't hide the field

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#66]
Environment

Chrome 47.0.2526.73

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Press on the search icon glass from the top right of page.

3) Set any text in search field.

4) Move mouse to the bottom of page.

actual: the search field is hide when mouse is not over.

expected: when a text is set in field do not hide the search field.

see attach!

**Comment by onetliviunicu** [comment]
[fiedl-hide.zip](https://github.com/appirio-tech/topcoder-app-r/files/211117/fiedl-hide.zip)

**Comment by callmekatootie** [comment]
@fnisen Is this a valid bug? UX issue?

**Comment by fnisen** [comment]
@callmekatootie it's a known UX issue, but I'll give credit. The expected behavior described is correct.
