### ISSUE TITLE
[Common] Current skill set is not displayed in Black

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#67]
Description
-----------------------------------------------------------------
[Common] Current skill set is not displayed in Black

Steps
-----------------------------------------------------------------
- Open the Topcoder Search Web Page

- https://www.topcoder-qa.com/search/members/?q=c%20%20

- Check the C++; Skill set

- The tags are not displayed in BALCK

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- Must display in BLACK

Actual result
-----------------------------------------------------------------
Current skill set is not displayed in Black

Environment
-----------------------------------------------------------------
Chrome 49.0.2623.112 m, 
FF 45.0.1, 
IE 11
iPhone 6s, Safari

Image/Video/JS Log
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![12](https://cloud.githubusercontent.com/assets/4592712/14402352/af58d582-fe50-11e5-840e-d6470afa5bc8.png)

**Comment by callmekatootie** [comment]
It displays those skill sets that it used to consider that to be part of the search
