### ISSUE TITLE
click the “Magnifying” button should close the search modal

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#68]
Mac 10.11.4 + Chrome 49.0

1. open https://www.topcoder-qa.com/search/members/?q=javascript
2. hover on the Magnifying button, the modal will show
3. click the button

expected: it should close the modal

actual: see screenshot

![qq20160409-33 2x](https://cloud.githubusercontent.com/assets/4590317/14402353/af85147a-fe65-11e5-9d4c-0471a7190ecd.png)

**Comment by callmekatootie** [comment]
Not valid. It does not have click but hover function
