### ISSUE TITLE
Search page conducts 2 XHR requests to the same /v3/members/ API endpoint

### ISSUE THREAD

**Issue by Colinh84** [appirio-tech/topcoder-app-r#69]
On search page, two XHR requests are always made to retrieve the users profile from api.topcoder-dev.com/v3/members/{username} on each pageload, with the initial request always resulting in HTTP 204 no content status code.

Steps:
- Open console on Chrome, navigate to "Network" tab
- Conduct a search
- Watch network requests, alwayss 2 XHR to same endpoint with one being a 204 status code.

Expected:
Should only be making one API request for user's profile info

Actual:
Redundant network XHR request on every page load.

Screenshot: http://i.imgur.com/yEuEasd.png

**Requirements**
- [ ] Please adhere to the code style specified in the readme.
- [ ] Make sure the component is rendered correctly on all screen sizes as specified in the designs

**Resources**
 -

**Comment by callmekatootie** [comment]
QA has this too - Cross origin requests have this feature. Please read it up

**Comment by nlitwin** [comment]
The first request is an OPTIONS, and the second one is a GET :)
