### ISSUE TITLE
Ignore spaces from search text

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#70]
Environment

Chrome 47.0.2526.73

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Press on the search icon glass from the top right of page.

3) Set any existing username in field and add a space before text.

actual: the search is not performed.

expected: ignore the spaces in search field.

see attach!

![spaces-before](https://cloud.githubusercontent.com/assets/18361424/14402361/014afb00-fe3c-11e5-94d3-dd29f20cd301.png)

**Comment by callmekatootie** [comment]
Can't reproduce
