### ISSUE TITLE
should set the max limit for the search text

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#71]
Mac 10.11.4 + Chrome 49.0

1. open https://www.topcoder-qa.com/search/members/?q=javascript
2. hover on the Magnifying button, the modal will show
3. enter a 500 chars string in it and search, observe

expected: it should set the max limit for the search string

actual: see screenshot, the page is not good

![qq20160409-34 2x](https://cloud.githubusercontent.com/assets/4590317/14402373/6a4d619a-fe66-11e5-8358-fed89102965b.png)

**Comment by callmekatootie** [comment]
in QA as well

**Comment by nlitwin** [comment]
Haha, good catch!
