### ISSUE TITLE
No autocomplete for search field

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#72]
Environment

Chrome 47.0.2526.73

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Press on the search icon glass from the top right of page.

3) Complete an existing name of user.

actual: no autocomplete list available.

expected: add autocomplete for list.

**Comment by callmekatootie** [comment]
Not a valid issue. Auto complete is a feature that does not exist. Not a bug
