### ISSUE TITLE
[Common] 'Return' button must display as 'Search' in Mobile keypad

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#73]
Description
-----------------------------------------------------------------
[Common] 'Return' button must display as 'Search' in Mobile keypad

Steps
-----------------------------------------------------------------
- Open the Topcoder Search Web Page

- https://www.topcoder-qa.com/search/members/?q=html

- Click Menu and click on the search

- Check the keypad

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- 'Return' button must display as 'Search' in Mobile keypad

Actual result
-----------------------------------------------------------------
'Return' button is displayed in keypad instead search

Environment
-----------------------------------------------------------------
iPhone 6s, Safari

Image/Video/JS Log
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![6](https://cloud.githubusercontent.com/assets/4592712/14407528/765c971a-feea-11e5-9755-2a2ff209aa81.PNG)

**Comment by nlitwin** [comment]
@vikasrohit Can we add `type="search"` to the input field in the new search bar?

**Comment by vikasrohit** [comment]
Ok. Got it. [Asana task](https://app.asana.com/0/95614844085038/113534202832110)

**Comment by nlitwin** [comment]
Closing since we are tracking in asana
