### ISSUE TITLE
No way to redirect to search page when no results

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#74]
Environment

Chrome 47.0.2526.73

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Press on the search icon glass from the top right of page.

3) Set an invalid text in search field(ex: testing 123 123).

4) Press enter to perform the search.

actual: no back option from the no results page.

expected: add back button or any back option.

see attach!

![no-back-button](https://cloud.githubusercontent.com/assets/18361424/14402381/b8f74c9a-fe3c-11e5-9294-fd5d404af8a6.png)

**Comment by callmekatootie** [comment]
There is no back because the search button is still available at the top right
