### ISSUE TITLE
NOTE TO BUG HUNT PARTICIPANTS

### ISSUE THREAD

**Issue by callmekatootie** [appirio-tech/topcoder-app-r#76]
@winterflame, @Colinh84, @sdgun, @madhusaha26 @swetaipec, @onetliviu

Please make sure you have the correct link for testing - https://www.topcoder-qa.com/search/members/?q=javascript

**Comment by Colinh84** [comment]
@callmekatootie this new link doesn't even have the top search bar implemented on the page.. Are you sure the original link at https://topcoder-dev.com/search/members/ isn't the most current?

**Comment by callmekatootie** [comment]
@Colinh84 Hover over the magnifying glass at the top right to open the search input:

![image](https://cloud.githubusercontent.com/assets/2317133/14402491/00316984-fe55-11e5-896f-82644e924ccb.png)
