### ISSUE TITLE
Clear field option is not available

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#77]
Environment

Chrome 47.0.2526.73

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Press on the search icon glass from the top right of page.

3) Set any text is field.

actual: no clear field option available in field.

expected: add clear all option on the left of field.

see attach!

![clear-all](https://cloud.githubusercontent.com/assets/18361424/14402401/4d224f64-fe3d-11e5-895c-86a763d1307c.png)
clear-all.png

**Comment by callmekatootie** [comment]
@fnisen Bug?

**Comment by nlitwin** [comment]
We are coming out with a new navigation soon, so we will probably not add this feature. @fnisen to confirm

**Comment by fnisen** [comment]
@callmekatootie this one is more a feature request than a bug

**Comment by onetliviunicu** [comment]
@fnisen , @callmekatootie , @nlitwin  if this is considered as a feature and can be implemented why is not accepted even is not a bug?

**Comment by callmekatootie** [comment]
Bug - A feature that exists that is not working as intended
Feature - A new functionality.

They didn't intend to have this feature - that of clearing the input.

If they had that feature, and if clicking on the "X" (which doesn't exist right now) would not clear the input, then that would be a bug. Providing the X itself is being taken as a feature here

**Comment by onetliviunicu** [comment]
ok, I understand, thank you!
