### ISSUE TITLE
Display search icon glass on the right of field

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#78]
Environment

Chrome 47.0.2526.73

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Press on the search icon glass from the top right of page.

3) Complete the search field with any text (ex: abcde ...).

4) Press enter to perform the action.

actual: the search icon glass is not available on the left of search field.

expected: add search icon glass on the left of field because the user must know that.

see attach!

![search-icon](https://cloud.githubusercontent.com/assets/18361424/14402412/b59114ea-fe3d-11e5-8fcc-3f1e74d10ad7.png)

**Comment by callmekatootie** [comment]
Not a valid issue. The magnifying glass is shown at the top
