### ISSUE TITLE
Showing the Static text as "Top Members in JavaScript"

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/topcoder-app-r#79]
1. Open the Topcoder Search Web Page 
2, Search for C++

Expected Result: Top Members in C++
Actual Result :   Top Members in JavaScript

Environment: Windows 7, Firefox 35

![image](https://cloud.githubusercontent.com/assets/16131461/14402402/52af4fa8-fe52-11e5-98ea-8c32ee5eb417.png)

**Comment by callmekatootie** [comment]
Not in QA
