### ISSUE TITLE
[iPad] search results are not seen after tapping the Menu button

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#80]
ios 9.3.1, iPad Retina

Mac 10.11.4 + Chrome 49.0

1. open https://www.topcoder-qa.com/search/members/?q=javascript
2. tap Menu, observe

expected:  search button should be taken out of the Menu 
 
actual: see screenshot

![qq20160409-35 2x](https://cloud.githubusercontent.com/assets/4590317/14402424/ea6601f6-fe67-11e5-8ed2-568c7a74dd36.png)

**Comment by callmekatootie** [comment]
Not a valid bug - the search is part of the menu - what's wrong with that?
