### ISSUE TITLE
No instance of required <title> tag found in <head> section of HTML

### ISSUE THREAD

**Issue by Colinh84** [appirio-tech/topcoder-app-r#81]
The <head> section of the HTML markup is missing a required <title> tag.

Steps:
- View Source, look at <head> section of markup on search page.

Expected:
<title></title> tag in <head> section of searchpage markup source.

Actual:
Required <title> tag missing.

**Requirements**
- [ ] Please adhere to the code style specified in the readme.
- [ ] Make sure the component is rendered correctly on all screen sizes as specified in the designs

**Resources**
 -

**Comment by callmekatootie** [comment]
@fnisen Bug? title html tag missing in header tag

**Comment by nlitwin** [comment]
Unless I misunderstand, I think the title is there, both in the tab and in the HTML `<head>` tag.

![image](https://cloud.githubusercontent.com/assets/5829188/14453251/8f8ca14e-0048-11e6-9a2a-0bfc5998c57d.png)

**Comment by fnisen** [comment]
@nlitwin - your call on this one

**Comment by nlitwin** [comment]
As far as I can tell, it looks correct to me, and there is no bug.

**Comment by Colinh84** [comment]
@nlitwin The <title> tag is missing from the source of the document, though it appears in the code inspector so it seems the entire tag is being generated by JS after loading the document. If you run the URL through W3C validator: https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.topcoder-qa.com%2Fsearch%2Fmembers%2F%3Fq%3Djava  it does not detect the title tag and comes back as invalid.

**Comment by nlitwin** [comment]
Yup yup! The title is dynamically added on every state change.
