### ISSUE TITLE
[Common] When searching the gray loading animation items goes beyond the table

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#82]
Description
-----------------------------------------------------------------
[Common] When searching the gray loading animation items goes beyond the table

Steps
-----------------------------------------------------------------
- Open the Topcoder Search Web Page

- https://www.topcoder-qa.com/search/members/?q=html

- Click Search and enter 'call'

- Check the Gray animation while loading

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- Must display within the table

Actual result
-----------------------------------------------------------------
When searching the gray loading animation items goes beyond the table

Environment
-----------------------------------------------------------------
iPhone 5, Safari

Image/Video/JS Log
-----------------------------------------------------------------

**Comment by sdgun** [comment]
http://www.screencast.com/t/Y2FPKX5C

**Comment by sdgun** [comment]
![3](https://cloud.githubusercontent.com/assets/4592712/14407515/28a9e4a0-feea-11e5-9775-807e19efed9b.PNG)

**Comment by callmekatootie** [comment]
Can't reproduce the issue
