### ISSUE TITLE
Search page HTML contains obsolete reference to Chrome Frame

### ISSUE THREAD

**Issue by Colinh84** [appirio-tech/topcoder-app-r#83]
in the HTML source code, the header contains:
<meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
the content attribute should not contain chrome=1, as this is meant to trigger the obsolete Chrome Frame which has long been discontinued, and serves no purpose.

Expected:
<meta http-equiv="X-UA-Compatible" content="IE=edge">

Actual:
<meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">

**Requirements**
- [ ] Please adhere to the code style specified in the readme.
- [ ] Make sure the component is rendered correctly on all screen sizes as specified in the designs

**Resources**
 -

**Comment by callmekatootie** [comment]
@fnisen Valid bug?

**Comment by nlitwin** [comment]
Hmm, it's part of the legacy code, and isn't causing any issues. @parthshah @aselbie Do we need/want to remove this?

**Comment by aselbie** [comment]
If it really is obsolete, and the research has been done, and it's trivial to remove, I would say go ahead and remove it. It's one less thing to wonder about, legacy or otherwise.

**Comment by nlitwin** [comment]
Sounds good! Let's classify this as a bug. I've begun removing it from our repos. Thanks @Colinh84
