### ISSUE TITLE
Obsolete "profile" attribute is used on <head> element in HTML markup

### ISSUE THREAD

**Issue by Colinh84** [appirio-tech/topcoder-app-r#84]
HTML markup on search page contains:
<head profile="http://www.w3.org/2005/10/profile">
Where the "profile" attribute is obsolete in HTML standards.

Steps:
View source on search page, look at <head> element. Find obsolete attribute.

Expected:
No profile attribute. The profile attribute on the head element is obsolete. To declare which meta terms are used in the document, instead register the names as meta extensions. To trigger specific UA behaviors, use a link element instead.

Actual:
Obsolete HTML attribute detected.

**Requirements**
- [ ] Please adhere to the code style specified in the readme.
- [ ] Make sure the component is rendered correctly on all screen sizes as specified in the designs

**Resources**
 -

**Comment by callmekatootie** [comment]
html5 does not need the attribute

**Comment by nlitwin** [comment]
@parthshah Was this needed at the time? https://github.com/appirio-tech/topcoder-app/commit/07338933fe09ab3b43945610a501aa3a53ba9f5b Can we safely remove it?

**Comment by nlitwin** [comment]
@parthshah Let me know if this needs to be removed
