### ISSUE TITLE
Search results in different way

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#85]
Environment

Chrome 47.0.2526.73

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Press on the search icon glass from the top right of page.

3) Search "Luca" and see the results as "JLucas".

4) Search "JLucas" and see as only one result is displayed.

expected: the users must be returned the same.

see attach!

![jlucas](https://cloud.githubusercontent.com/assets/18361424/14402439/6b5697f0-fe3e-11e5-8479-5db4dc5ee99d.png)

**Comment by callmekatootie** [comment]
Not a bug. I would say that Luca is a substring of JLucas and thus JLucas was shown when searching for Luca - but the other is not true.
