### ISSUE TITLE
[Common] Skill set gets larger when we go to Landscape Mode; But "Skills" title won't

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#87]
Description
-----------------------------------------------------------------
[Common] Skill set gets larger when we go to Landscape Mode; But "Skills" title won't

Steps
-----------------------------------------------------------------
- Open the Topcoder Search Web Page

- https://www.topcoder-qa.com/search/members/?q=html

- Click Search and enter 'call'

- Go to Landscape Mode

- Check the "Skills:" title and the skill tags

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- Skills title must match with the other tags

Actual result
-----------------------------------------------------------------
Skill set gets larger when we go to Landscape Mode; But "Skills" title won't

Environment
-----------------------------------------------------------------
iPhone 6s, Safari
iPhone 5, Safari

Image/Video/JS Log
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![5](https://cloud.githubusercontent.com/assets/4592712/14407524/51343c0e-feea-11e5-81be-e7a9687a632a.PNG)

**Comment by callmekatootie** [comment]
Can't make out if bug or feature @fnisen @nlitwin

**Comment by nlitwin** [comment]
This is a bug
