### ISSUE TITLE
Do not perform the search when no text in search field

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#88]
Environment

Chrome 47.0.2526.73

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Press on the search icon glass from the top right of page.

3) Without set any text in search field press enter.

actual: the search is performed even no text was set,

expected: do not perform search function when no text set in field.

**Comment by callmekatootie** [comment]
Same as #22
