### ISSUE TITLE
“No results found” page should be redesigned

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#89]
Mac 10.11.4 + Chrome 49.0

1. open https://www.topcoder-qa.com/search/members/?q=n
2. observe

expected: it should be redesigned.

actual: see screenshot, it looks like a broken page or something fatal has happened.

![qq20160409-37 2x](https://cloud.githubusercontent.com/assets/4590317/14402454/f8f64130-fe68-11e5-8402-499dcbda5bac.png)

**Comment by callmekatootie** [comment]
The text below seems to be clear that no results were found. Can't understand why you think its broken
