### ISSUE TITLE
Text is dispayed near margin of field

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#90]
Environment

Chrome 47.0.2526.73

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Press on the search icon glass from the top right of page.

actual: "FIND MEMBER" text is displayed immediately near the left margin of search field.

ex
![text-near-field](https://cloud.githubusercontent.com/assets/18361424/14402470/7d592e76-fe3f-11e5-95b7-f58505538419.png)
pected: set a space after the margin and text.

**Comment by callmekatootie** [comment]
Same as #51
