### ISSUE TITLE
[iPad] no placeholder text 

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#91]
ios 9.3.1, iPad Retina, safari
1. open https://www.topcoder-qa.com/search/members/?q=javascript
2. click Menu , observe the search box

expected: it should has placeholder text "FIND MEMBERS", like the desktop version

actual: see screenshot
![qq20160409-38 2x](https://cloud.githubusercontent.com/assets/4590317/14402472/7920b1ba-fe69-11e5-940a-b7237ceb41e6.png)

**Comment by callmekatootie** [comment]
I think this depends on the browser. iirc, some remove the placeholder text on focus, some don't

@fnisen @nlitwin bug?

**Comment by nlitwin** [comment]
This is functioning as expected, and we won't be updating anything related to the old navigation, since we're coming out with an entirely new navigation soon.

**Comment by fnisen** [comment]
@callmekatootie - we can give credit for this one, but won't fix for now, as @nlitwin said.
