### ISSUE TITLE
Set the text at the begin of the field

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#92]
Environment

Chrome 47.0.2526.73

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Press on the search icon glass from the top right of page.

3) Add multiple blankspaces in field.

4) Set any text in field.

actual: even the focus is on the middle of the field the text is set in that position.

expected: set automatically the focus at the begin of the field.

see attach!

![set-text-at-begin](https://cloud.githubusercontent.com/assets/18361424/14402484/da72beba-fe3f-11e5-8838-d511f08ef123.png)

**Comment by callmekatootie** [comment]
Not a bug - the cursor will always begin from end of line unless you explicitly take it to the middle
