### ISSUE TITLE
Icon overlaps username in top bar

### ISSUE THREAD

**Issue by Colinh84** [appirio-tech/topcoder-app-r#94]
On the top meu bar, on the far right, the user icon appears on top of the displayed username.

Expected:
No overlap of username with icon

Actual:
Icon is covering username.

Screenshot: http://i.imgur.com/jx03WnF.png

**Requirements**
- [ ] Please adhere to the code style specified in the readme.
- [ ] Make sure the component is rendered correctly on all screen sizes as specified in the designs

**Resources**
 -

**Comment by callmekatootie** [comment]
Same as #58
