### ISSUE TITLE
not sure the meaning of the badge color 

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#95]
Mac 10.11.4 + Chrome 49.0

1. open https://www.topcoder-qa.com/search/members/?q=java
2. observe the results (see color of the user avatar)

expected: hovering on the badge should show some tips about the meaning

actual: see screenshot, no tips

![qq20160409-40 2x](https://cloud.githubusercontent.com/assets/4590317/14402517/d12a9604-fe6a-11e5-9cf2-12cbc763e911.png)

**Comment by callmekatootie** [comment]
Not sure if bug @fnisen @nlitwin

**Comment by nlitwin** [comment]
This isn't a bug. We are currently building tooltips that will help the user understand various elements on the page, but this is part of version 2, not version 1.

**Comment by fnisen** [comment]
Yeah, more of a feature request than a bug.
