### ISSUE TITLE
No back option after results are dispayed

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#98]
Environment

Chrome 47.0.2526.73

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Press on the search icon glass from the top right of page.

3) Set a word "text" in search field.

4) Press enter to perform the action.

5) Try to back.

actual: no back option after the results are displayed.

expected: add a back option.

see attach!

![no-back-option](https://cloud.githubusercontent.com/assets/18361424/14402527/4b5b2dfa-fe41-11e5-9e40-29a24539ec7a.png)

**Comment by callmekatootie** [comment]
Why do you need to go back? If you want to go to previous search result - hit browser back. If you want to search, use the search above
