### ISSUE TITLE
[Common] Wrong users listed when we search the skill set 'Windows'

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app-r#99]
Description
-----------------------------------------------------------------
[Common] Wrong users listed when we search the skill set 'Windows'

Steps
-----------------------------------------------------------------
- Open the Topcoder Search Web Page

- https://www.topcoder-qa.com/search/members/?q=windows

- Check the Skill set

- When user search for 'windows' search will list the users that won't have that skill set in their profile. This can be seen when user search for other skills as well.

Expected result
-----------------------------------------------------------------
Must fix the Issue,
- Must display the relevant users

Actual result
-----------------------------------------------------------------
Wrong users listed when we search the skill set 'Windows'

Environment
-----------------------------------------------------------------
Chrome 49.0.2623.112 m, 
FF 45.0.1, 
iPhone 6s, Safari
iPhone 5, Safari

Image/Video/JS Log
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![16](https://cloud.githubusercontent.com/assets/4592712/14402534/7562a2a8-fe56-11e5-8628-6a7ed1a6b8d4.png)

**Comment by callmekatootie** [comment]
Duplicate bug. Can't locate the ticket but this one's come before
